#!/bin/bash
# https://github.com/P3TERX/Actions-OpenWrt
# File name: diy-part1.sh
# Description: OpenWrt DIY script part 1 (Before Update feeds)

set -euo pipefail  # 严格报错模式：任一非条件命令失败立即终止

# === 1. 软件源配置 ===
# 添加 QModem 软件源
echo 'src-git qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default

# === 2. 提取无线网卡驱动（精准对齐 25.12 分支时代） ===
git clone --depth 1 -b openwrt-25.12 --filter=blob:none --sparse https://github.com/immortalwrt/immortalwrt.git package/immortalwrt_temp
cd package/immortalwrt_temp
git sparse-checkout set package/kernel/aic8800
cd ../..
cp -r package/immortalwrt_temp/package/kernel/aic8800 package/kernel/aic8800
rm -rf package/immortalwrt_temp

# === 3. 安装 argon 主题
git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

# === 4. 管理蓝牙设备的LuCI
git clone https://github.com/I-agree/luci-app-bluetooth.git package/luci-app-bluetooth

# === 5. 磁盘扩容
git clone https://github.com/sirpdboy/luci-app-partexp.git package/luci-app-partexp

# ======================== 【统一下载与文件校验中心】 ========================
echo "📥 开始统一拉取 H29K 编译所需的核心外置资源..."

# 创建全局所需的所有目录架构 (新增 files/www 网页容器支撑)
mkdir -p target/linux/rockchip/files/arch/arm64/boot/dts/rockchip \
         package/boot/uboot-rockchip/configs \
         package/boot/uboot-rockchip/dts \
         target/linux/rockchip/image \
         package/boot/rkbin \
         files/etc/config/screen \
         files/etc/docker/mediamtx \
         files/etc/init.d \
         files/etc/fonts/conf.d \
         files/usr/bin \
         files/www \
         package/boot/uboot-rockchip/patches \
         files/usr/share/docker-images

BASE_URL="https://raw.githubusercontent.com/I-agree/H29K/main"
LOGO_URL="https://raw.githubusercontent.com/I-agree/H29K/main/JPG"

# [工具函数] 统一的下载与基础大小校验
download_and_check() {
    local url="$1"
    local dest="$2"
    echo "正在下载: $dest ..."
    if ! curl -fsSL --retry 3 --retry-delay 2 --connect-timeout 10 "$url" -o "$dest"; then
        echo "❌ 错误: $url 网络请求或连接失败！"
        exit 1
    fi
    if [ ! -s "$dest" ]; then
        echo "❌ 错误: $dest 下载成功但文件为空！"
        exit 1
    fi
}

# --- 批量下载核心底座组件 ---
download_and_check "${BASE_URL}/target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3528-hinlink-h29k.dts" "target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3528-hinlink-h29k.dts"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink-h29k-rk3528_defconfig" "package/boot/uboot-rockchip/configs/hinlink-h29k-rk3528_defconfig"
download_and_check "${BASE_URL}/target/linux/rockchip/image/armv8.mk" "target/linux/rockchip/image/armv8.mk"
download_and_check "${BASE_URL}/target/linux/rockchip/Makefile" "target/linux/rockchip/Makefile"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/Makefile" "package/boot/uboot-rockchip/Makefile"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k-u-boot.dtsi" "package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k-u-boot.dtsi"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/900-fix-mb-missing-header.patch" "package/boot/uboot-rockchip/patches/900-fix-mb-missing-header.patch"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/901-fix-dwc3-dma-proto.patch" "package/boot/uboot-rockchip/patches/901-fix-dwc3-dma-proto.patch"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k.dts" "package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k.dts"
download_and_check "${BASE_URL}/package/boot/rkbin/Makefile" "package/boot/rkbin/Makefile"

# --- 统一拉取应用层开机 LOGO 组 ---
for i in 1 2 3; do
    download_and_check "${LOGO_URL}/LOGO${i}.jpg" "files/etc/config/screen/LOGO${i}.jpg"
done

# ==============================================================================
echo "🚀 [diy-part1.sh] 软件源与独立包与配置文件下载圆满完成！"

# ======================== 【H29K 主线内核配置合并注入】 ========================
CONFIG_FILE="target/linux/rockchip/armv8/config-6.12"

echo "📝 正在精准注入官方 OpenWrt 25.12 专属内核配置文件: $CONFIG_FILE"

# ⚠️ 使用 sed 原位替换，防止 Kconfig 忽略 EOF 末尾追加的重复项
sed -i 's/^CONFIG_ARM64_SVE=y$/# CONFIG_ARM64_SVE is not set/' "$CONFIG_FILE"
sed -i 's/^CONFIG_CMA_SIZE_MBYTES=16$/CONFIG_CMA_SIZE_MBYTES=128/' "$CONFIG_FILE"
sed -i 's/^CONFIG_CMA_AREAS=7$/CONFIG_CMA_AREAS=8/' "$CONFIG_FILE"
sed -i 's/^CONFIG_DWMAC_DWC_QOS_ETH=y$/# CONFIG_DWMAC_DWC_QOS_ETH is not set/' "$CONFIG_FILE"
sed -i 's/^# CONFIG_PARTITION_ADVANCED is not set$/CONFIG_PARTITION_ADVANCED=y/' "$CONFIG_FILE"

cat >> "$CONFIG_FILE" << 'EOF'

# ====================== 批量关闭无用大类（不影响WiFi/USB/网口/屏幕/媒体） ======================
# 无音频硬件，关闭整套声卡
# CONFIG_SOUND is not set
# 无工业传感器ADC/陀螺仪
# CONFIG_IIO is not set
# 无外置硬件RTC时钟芯片（修正：内核标准开关RTC_CLASS，删除无效CONFIG_RTC）
# CONFIG_RTC_CLASS is not set
# RK3528无PCI总线外设
# CONFIG_PCI is not set
# 【删除】CONFIG_VIRTUALIZATION（无该顶层总开关，配置无效）
# 无FPGA可编程逻辑
# CONFIG_FPGA is not set
# 工业总线全部无用
# CONFIG_CAN is not set
# CONFIG_PECI is not set
# CONFIG_HTE is not set
# CONFIG_CDX_BUS is not set
# 关闭用户态加密，仅内核内置解压保留
# CONFIG_CRYPTO_USER is not set
CONFIG_CRYPTO_MANAGER_DISABLE_TESTS=y

# 内核调试/单元测试/性能监控/追踪全套关闭（消灭menuconfig NEW弹窗）
# CONFIG_DEBUG_KERNEL is not set
# CONFIG_KUNIT is not set
# CONFIG_PERF_EVENTS is not set
# CONFIG_TRACEPOINTS is not set
# CONFIG_FTRACE is not set
# CONFIG_FUNCTION_TRACER is not set
# CONFIG_COREDUMP is not set
# CONFIG_STACKTRACE is not set
# CONFIG_FRAME_POINTER is not set
# CONFIG_KALLSYMS is not set
# CONFIG_FAULT_INJECTION is not set
# CONFIG_DYNAMIC_DEBUG is not set

# GPS、远程处理器、NVMEM离线存储无用
# CONFIG_NVMEM is not set
# CONFIG_REMOTEPROC is not set
# CONFIG_RPMSG is not set
# CONFIG_GNSS is not set

# SATA/NVME/IDE本地硬盘整套关闭（修正：删除无效CONFIG_NV，替换标准host/target）
# CONFIG_SCSI is not set
# CONFIG_ATA is not set
# CONFIG_NVME_HOST is not set
# CONFIG_NVME_TARGET is not set

# 【移除风险项】# CONFIG_MISC_DEVICES is not set （drivers/misc包含RK平台基础杂设备，关闭会外设失效）

# 看门狗、内存硬件纠错
# CONFIG_WATCHDOG is not set
# CONFIG_EDAC is not set
# 服务器高速IB网卡
# CONFIG_INFINIBAND is not set
# 老式PS2、并口
# CONFIG_SERIO is not set
# CONFIG_PARPORT is not set
# 多电池充电PMIC、电量计
# CONFIG_POWER_SUPPLY is not set
# 交换机、二层网桥无用
# CONFIG_NET_DSA is not set
# CONFIG_BRIDGE is not set
# 废弃/测试驱动合集
# CONFIG_STAGING is not set

# 软件RAID/LVM/dm加密、虚拟块驱动全套关闭
# CONFIG_MD is not set
# CONFIG_BLK_DEV is not set

# 重要：底层块设备核心必须保留，不可关闭
CONFIG_BLOCK=y

# ======================
# CONFIG_VIRTUALIZATION is not set
# CONFIG_XEN is not set
# CONFIG_VIRT_DRIVERS is not set
# CONFIG_VHOST_MENU is not set
# CONFIG_VHOST_NET is not set
# CONFIG_VDPA is not set
# CONFIG_VIRTIO_CONSOLE is not set
# CONFIG_DEBUG_KERNEL is not set
# CONFIG_FTRACE is not set
# CONFIG_TRACEPOINTS is not set
# CONFIG_KUNIT is not set
# CONFIG_PERF_EVENTS is not set
# CONFIG_KALLSYMS is not set
# CONFIG_STACKTRACE is not set
# CONFIG_FRAME_POINTER is not set
# CONFIG_DYNAMIC_DEBUG is not set
# CONFIG_DEBUG_FS is not set
# CONFIG_UBSAN is not set
# CONFIG_KASAN is not set
# CONFIG_KFENCE is not set
# CONFIG_PROFILING is not set
# CONFIG_RELAY is not set
# CONFIG_BOOT_CONFIG is not set
# CONFIG_AUDIT is not set
# CONFIG_CGROUPS is not set
# CONFIG_USER_NS is not set
# CONFIG_SYSVIPC is not set
# CONFIG_POSIX_MQUEUE is not set
# CONFIG_WATCH_QUEUE is not set
# CONFIG_CHECKPOINT_RESTORE is not set
# CONFIG_TASKSTATS is not set
# CONFIG_PSI is not set
# CONFIG_SECCOMP_CACHE_DEBUG is not set
# CONFIG_NO_HZ is not set
# CONFIG_NO_HZ_FULL is not set
# CONFIG_HIGH_RES_TIMERS is not set
# CONFIG_PM_AUTOSLEEP is not set
# CONFIG_PM_USERSPACE_AUTOSLEEP is not set
# CONFIG_PM_WAKELOCKS is not set
# CONFIG_PM_DEBUG is not set
# CONFIG_WQ_POWER_EFFICIENT_DEFAULT is not set
# CONFIG_CPU_IDLE_GOV_LADDER is not set
# CONFIG_CPU_IDLE_GOV_TEO is not set
# CONFIG_PCI is not set
# CONFIG_CAN is not set
# CONFIG_PECI is not set
# CONFIG_HTE is not set
# CONFIG_CDX_BUS is not set
# CONFIG_SERIO is not set
# CONFIG_PARPORT is not set
# CONFIG_SSB is not set
# CONFIG_BCMA is not set
# CONFIG_COMEDI is not set
# CONFIG_GREYBUS is not set
# CONFIG_MCB is not set
# CONFIG_IPACK is not set
# CONFIG_SIOX is not set
# CONFIG_SLIMBUS is not set
# CONFIG_INTERCONNECT is not set
# CONFIG_MOST is not set
# CONFIG_SCSI is not set
# CONFIG_ATA is not set
# CONFIG_NVME_HOST is not set
# CONFIG_NVME_TARGET is not set
# CONFIG_MD is not set
# CONFIG_BLK_DEV is not set
# CONFIG_TARGET_CORE is not set
# CONFIG_DAX is not set
# CONFIG_NVMEM is not set
# CONFIG_FTL is not set
# CONFIG_NFTL is not set
# CONFIG_INFTL
# CONFIG_IIO is not set
# CONFIG_HWMON is not set
# CONFIG_WATCHDOG is not set
# CONFIG_EDAC is not set
# CONFIG_INFINIBAND is not set
# CONFIG_POWER_SUPPLY is not set
# CONFIG_RPMSG is not set
# CONFIG_REMOTEPROC is not set
# CONFIG_GNSS is not set
# CONFIG_STAGING is not set
# CONFIG_FPGA is not set
# CONFIG_SOUND is not set
# CONFIG_CRYPTO_USER is not set
# CONFIG_CRYPTO_TEST is not set

# =================================================================
# 🔧 H29K 硬件对齐修正 (RK3528 内置 Naneng CombPHY)
# =================================================================
# ❌ 移除所有外置 PHY 驱动 (H29K 无独立 RTL8211/Micrel/KSZ PHY)
# CONFIG_MICREL_PHY is not set
# CONFIG_REALTEK_PHY is not set
# CONFIG_MOTORCOMM_PHY is not set
# CONFIG_MEDIATEK_GE_PHY is not set

# ✅ RK3528 内置千兆 RGMII PHY (Naneng CombPHY)
CONFIG_PHY_ROCKCHIP_NANENG_COMBO_PHY=y
CONFIG_PHYLINK=y
CONFIG_FIXED_PHY=y

# =================================================================
# 📡 蓝牙完整协议栈 (AIC8800 SDIO WiFi+BT二合一)
# =================================================================
CONFIG_BT=y
CONFIG_BT_BREDR=y
CONFIG_BT_LE=y
CONFIG_BT_RFCOMM=y
CONFIG_BT_RFCOMM_TTY=y
CONFIG_BT_BNEP=y
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y
CONFIG_BT_HIDP=y

# 启用SDIO蓝牙，适配AIC8800复合模组
CONFIG_BT_HCIBTSDIO=y

# 禁用USB、UART类型蓝牙传输
# CONFIG_BT_HCIBTUSB is not set
# CONFIG_BT_HCIUART is not set

# AIC8800 SDIO蓝牙硬件支持开关
CONFIG_AIC8800_SDIO_BT_SUPPORT=y

# =================================================================
# 🚫 关闭 SimpleDRM (避免与 ST7789V SPI 屏抢占 fb0)
# =================================================================
# CONFIG_DRM_SIMPLEDRM is not set

# =================================================================
# 固件加载配置（彻底规避NEW交互式报错）
# =================================================================
CONFIG_FW_LOADER=y
CONFIG_FW_LOADER_USER_HELPER=y
CONFIG_FW_LOADER_USER_HELPER_FALLBACK=y
CONFIG_FW_LOADER_COMPRESS=y

# 字符串类型必须显式赋值，不能用#注释禁用
CONFIG_EXTRA_FIRMWARE=""
CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware"

# 锁定自动选中依赖项
# CONFIG_FW_LOADER_PAGED_BUF is not set
# CONFIG_FW_LOADER_SYSFS is not set

# 锁定压缩子模块
# CONFIG_FW_LOADER_COMPRESS_XZ is not set
# CONFIG_FW_LOADER_COMPRESS_ZSTD is not set

# 关闭无用固件相关功能
# CONFIG_FW_LOADER_DEBUG is not set
# CONFIG_RUST_FW_LOADER_ABSTRACTIONS is not set
# CONFIG_FW_CACHE is not set
# CONFIG_FW_UPLOAD is not set

# =================================================================
# 通用驱动基础配置 提前规避drivers/base/staging模块NEW弹窗
# =================================================================
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
# CONFIG_DEVTMPFS_SAFE is not set
CONFIG_STANDALONE=y
CONFIG_PREVENT_FIRMWARE_BUILD=y
# CONFIG_UEVENT_HELPER is not set
# CONFIG_ALLOW_DEV_COREDUMP is not set
# CONFIG_DEBUG_DRIVER is not set
# CONFIG_DMA_SHARED_BUFFER is not set

# 关闭废弃Staging驱动，屏蔽rtl8723bs/rtllib等老旧无线NEW弹窗
# CONFIG_STAGING is not set

# =================================================================
# 🔧 前次分析缺失项修复 + 【关键修复：全部cfg80211+mac80211配置固化防交互弹窗】
# =================================================================
# SFC MTD 分区解析
CONFIG_MTD_CHAR=y
CONFIG_MTD_OF_PARTS=y

# WiFi 协议栈 (AIC8800 SDIO 必需)
CONFIG_CFG80211=y
CONFIG_NL80211=y
CONFIG_CFG80211_HEADERS=y
# 禁用nl80211工厂测试命令，消除NEW交互式弹窗
# CONFIG_NL80211_TESTMODE is not set
CONFIG_CFG80211_WEXT=y
CONFIG_CFG80211_CRDA_SUPPORT=y
CONFIG_CFG80211_USE_KERNEL_REGDB_KEYS=y
CONFIG_CFG80211_DEFAULT_REGDOM=y
# 无线默认省电模式，规避NEW弹窗
CONFIG_CFG80211_DEFAULT_PS=y
# 关闭无线开发调试警告
# CONFIG_CFG80211_DEVELOPER_WARNINGS is not set
# 关闭无线认证高级选项
# CONFIG_CFG80211_CERTIFICATION_ONUS is not set
# 关闭cfg80211调试文件系统节点
# CONFIG_CFG80211_DEBUGFS is not set

# 固化cfg80211衍生配置，防止新增交互
# CONFIG_CFG80211_REQUIRE_SIGNED_REGDB is not set
# CONFIG_CFG80211_REG_CELLULAR_HINTS is not set
# CONFIG_CFG80211_REG_RELAX_NO_IR is not set
# CONFIG_CFG80211_KUNIT_TEST is not set
# CONFIG_LIB80211_DEBUG is not set
# 字符串类型必须显式赋值
CONFIG_CFG80211_EXTRA_REGDB_KEYDIR=""

CONFIG_MAC80211=y
# mac80211速率自适应核心配置，解决本次MINSTREL交互报错
CONFIG_MAC80211_RC_MINSTREL=y
CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y
# 关闭mesh、无线LED、各类调试功能
# CONFIG_MAC80211_MESH is not set
# CONFIG_MAC80211_LEDS is not set
# CONFIG_MAC80211_DEBUGFS is not set
# CONFIG_MAC80211_MESSAGE_TRACING is not set
# CONFIG_MAC80211_DEBUG_MENU is not set
# 关闭无线仿真测试
# CONFIG_MAC80211_HWSIM is not set

CONFIG_WLAN=y

# 全部内核WiFi厂商驱动禁用，杜绝批量交互弹窗
# CONFIG_WLAN_VENDOR_ADMTEK is not set
# CONFIG_WLAN_VENDOR_ATH is not set
# CONFIG_WLAN_VENDOR_ATMEL is not set
# CONFIG_WLAN_VENDOR_BROADCOM is not set
# CONFIG_WLAN_VENDOR_INTEL is not set
# CONFIG_WLAN_VENDOR_INTERSIL is not set
# CONFIG_WLAN_VENDOR_MARVELL is not set
# CONFIG_WLAN_VENDOR_MEDIATEK is not set
# CONFIG_WLAN_VENDOR_MICROCHIP is not set
# CONFIG_WLAN_VENDOR_PURELIFI is not set
# CONFIG_WLAN_VENDOR_RALINK is not set
# CONFIG_WLAN_VENDOR_REALTEK is not set
# CONFIG_WLAN_VENDOR_RSI is not set
# CONFIG_WLAN_VENDOR_SILABS is not set
# CONFIG_WLAN_VENDOR_ST is not set
# CONFIG_WLAN_VENDOR_TI is not set
# CONFIG_WLAN_VENDOR_ZYDAS is not set
# CONFIG_WLAN_VENDOR_QUANTENNA is not set

# 关闭mac80211无线硬件仿真测试工具
# CONFIG_MAC80211_HWSIM is not set

# 关闭以太网转WiFi虚拟封装驱动
# CONFIG_VIRT_WIFI is not set

# gpio-keys 驱动修正 (替代错误的 KEYBOARD_GPIO)
# CONFIG_KEYBOARD_GPIO is not set
CONFIG_INPUT_GPIO_KEYS=y

# =================================================================
# 🌐 网络核心与 IPv6
# =================================================================
CONFIG_NET=y
CONFIG_NETDEVICES=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_IPV6_ROUTER_PREF=y
CONFIG_IPV6_ROUTE_INFO=y
CONFIG_IPV6_SIT=y
CONFIG_IPV6_NDISC_NODETYPE=y
CONFIG_NF_TABLES_BRIDGE=y

# =================================================================
# 🚀 RK3528 GMAC (Synopsys DWMAC 4.20a)
# =================================================================
CONFIG_NET_VENDOR_STMICRO=y
CONFIG_STMMAC_PLATFORM=y
CONFIG_DWMAC_ROCKCHIP=y
CONFIG_PTP_1588_CLOCK_OPTIONAL=y

# =================================================================
# 💾 MMC/SDIO (AIC8800 WiFi)
# =================================================================
CONFIG_MMC_PWRSEQ_SIMPLE=y
CONFIG_MMC_PWRSEQ_EMMC=y

# =================================================================
# 📂 文件系统
# =================================================================
CONFIG_LIB_UUID=y
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_XATTR=y
CONFIG_SQUASHFS_ZSTD=y
CONFIG_OVERLAY_FS=y
CONFIG_OVERLAY_FS_POSIX_ACL=y
CONFIG_FAT_FS=y
CONFIG_VFAT_FS=y
CONFIG_FAT_DEFAULT_CODEPAGE=936
CONFIG_FAT_DEFAULT_IOCHARSET="utf8"
CONFIG_FAT_DEFAULT_UTF8=y
CONFIG_EXFAT_FS=y
CONFIG_EXFAT_DEFAULT_IOCHARSET="utf8"
CONFIG_NLS_UTF8=y
CONFIG_NLS_CODEPAGE_936=y

# =================================================================
# 🖥️ 显示: ST7789V SPI 屏 (无 HDMI/SimpleDRM)
# =================================================================
CONFIG_SPI=y
CONFIG_SPI_ROCKCHIP=y
CONFIG_SPI_ROCKCHIP_SFC=y
CONFIG_MTD=y
CONFIG_MTD_BLOCK=y
CONFIG_MTD_SPI_NOR=y
CONFIG_GPIOLIB=y
CONFIG_DRM=y
CONFIG_DRM_KMS_HELPER=y
CONFIG_DRM_PANEL=y
CONFIG_DRM_BRIDGE=y
CONFIG_DRM_PANEL_BRIDGE=y
CONFIG_FB=y
CONFIG_FB_SYS_FILLRECT=y
CONFIG_FB_SYS_COPYAREA=y
CONFIG_FB_SYS_IMAGEBLIT=y
CONFIG_FB_SYS_FOPS=y
CONFIG_FB_DEFERRED_IO=y
CONFIG_FB_MODE_HELPERS=y
CONFIG_FB_BACKLIGHT=y
CONFIG_BACKLIGHT_CLASS_DEVICE=y
CONFIG_BACKLIGHT_PWM=y
CONFIG_DRM_PANEL_SITRONIX_ST7789V=y

# =================================================================
# 🎥 VPU/RGA/UVC
# =================================================================
CONFIG_MEDIA_SUPPORT=y
CONFIG_MEDIA_CONTROLLER=y
CONFIG_VIDEO_DEV=y
CONFIG_VIDEO_V4L2_SUBDEV_API=y
CONFIG_MEDIA_CAMERA_SUPPORT=y
CONFIG_MEDIA_PLATFORM_SUPPORT=y
CONFIG_USB_VIDEO_CLASS=y
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y
CONFIG_VIDEO_ROCKCHIP_RGA=y
CONFIG_V4L_MEM2MEM_DRIVERS=y
CONFIG_VIDEO_HANTRO=y
CONFIG_VIDEO_HANTRO_ROCKCHIP=y
# CONFIG_VIDEO_HANTRO_HEVC_RFC is not set

# =================================================================
# 🛡️ 温控/RNG/IR/RFKill/LEDs/串口
# =================================================================
CONFIG_THERMAL=y
CONFIG_THERMAL_OF=y
CONFIG_THERMAL_HWMON=y
CONFIG_ROCKCHIP_THERMAL=y
CONFIG_HW_RANDOM=y
CONFIG_HW_RANDOM_ROCKCHIP=y
CONFIG_IR_CORE=y
CONFIG_IR_GPIO=y
CONFIG_RFKILL=y
CONFIG_RFKILL_GPIO=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_8250_DW=y
CONFIG_SERIAL_8250_DWLIB=y
CONFIG_SERIAL_OF_PLATFORM=y

# =================================================================
# 📦 CIFS/NetFS 模块
# =================================================================
CONFIG_NETFS_SUPPORT=m
CONFIG_FSCACHE=y
CONFIG_CIFS=m
CONFIG_CIFS_ALLOW_INSECURE_LEGACY=y
CONFIG_CIFS_XATTR=y
CONFIG_CIFS_POSIX=y

# =================================================================
# 🔄 TCP BBR + FQ
# =================================================================
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=y
CONFIG_DEFAULT_BBR=y
CONFIG_DEFAULT_NET_CONG=bbr
CONFIG_NET_SCHED=y
CONFIG_NET_SCH_FQ=y
CONFIG_DEFAULT_QDISC=fq

# =================================================================
# 🔌 USB OTG/Dual Role（内核DWC3 XHCI 官方最优方案，匹配DTS usb_host0_xhci节点，RK3528自动降级USB2）
# =================================================================
CONFIG_USB_SUPPORT=y
CONFIG_USB=y
CONFIG_USB_GADGET=y
CONFIG_USB_OTG=y
CONFIG_USB_ROLE_SWITCH=y

# USB通用基础配置 防弹窗
# CONFIG_USB_LED_TRIG is not set
CONFIG_USB_ULPI_BUS=y
# CONFIG_USB_CONN_GPIO is not set
# CONFIG_USB_PCI is not set
# CONFIG_USB_PCI_AMD is not set
# CONFIG_USB_ANNOUNCE_NEW_DEVICES is not set
CONFIG_USB_DEFAULT_PERSIST=y
# CONFIG_USB_FEW_INIT_RETRIES is not set
# CONFIG_USB_DYNAMIC_MINORS is not set
# CONFIG_USB_OTG_PRODUCTLIST is not set
# CONFIG_USB_OTG_DISABLE_EXTERNAL_HUB is not set
# CONFIG_USB_OTG_FSM is not set
# CONFIG_USB_LEDS_TRIGGER_USBPORT is not set
# 整型参数必须显式赋值
CONFIG_USB_AUTOSUSPEND_DELAY=2
CONFIG_USB_DEFAULT_AUTHORIZATION_MODE=1
# CONFIG_USB_MON is not set

# DWC3控制器核心配置
CONFIG_USB_DWC3=y
# CONFIG_USB_DWC3_ULPI is not set
# DWC3互斥三模式：仅启用双角色OTG
# CONFIG_USB_DWC3_HOST is not set
# CONFIG_USB_DWC3_GADGET is not set
CONFIG_USB_DWC3_DUAL_ROLE=y

# 仅保留瑞芯微DWC3平台驱动，关闭所有其他厂商胶水驱动
CONFIG_USB_DWC3_ROCKCHIP=y
# CONFIG_USB_DWC3_OMAP is not set
# CONFIG_USB_DWC3_EXYNOS is not set
# CONFIG_USB_DWC3_PCI is not set
# CONFIG_USB_DWC3_HAPS is not set
# CONFIG_USB_DWC3_KEYSTONE is not set
# CONFIG_USB_DWC3_MESON_G12A is not set
# CONFIG_USB_DWC3_OF_SIMPLE is not set
# CONFIG_USB_DWC3_ST is not set
# CONFIG_USB_DWC3_QCOM is not set
# CONFIG_USB_DWC3_IMX8MP is not set
# CONFIG_USB_DWC3_XILINX is not set
# CONFIG_USB_DWC3_AM62 is not set
# CONFIG_USB_DWC3_OCTEON is not set
# CONFIG_USB_DWC3_RTK is not set

# XHCI主机控制器
CONFIG_USB_XHCI_HCD=y
# CONFIG_USB_XHCI_DBGCAP is not set
# CONFIG_USB_XHCI_PCI_RENESAS is not set
CONFIG_USB_XHCI_DWC3=y
CONFIG_USB_XHCI_PLATFORM=y

# 禁用所有老旧及第三方USB主机控制器
# CONFIG_USB_EHCI_HCD is not set
# CONFIG_USB_OHCI_HCD is not set
# CONFIG_USB_C67X00_HCD is not set
# CONFIG_USB_OXU210HP_HCD is not set
# CONFIG_USB_ISP116X_HCD is not set
# CONFIG_USB_MAX3421_HCD is not set
# CONFIG_USB_UHCI_HCD is not set
# CONFIG_USB_SL811_HCD is not set
# CONFIG_USB_R8A66597_HCD is not set
# CONFIG_USB_HCD_TEST_MODE is not set

# USB设备类驱动
CONFIG_USB_STORAGE=y
# CONFIG_USB_STORAGE_DEBUG is not set
# CONFIG_USB_STORAGE_REALTEK is not set
# CONFIG_USB_STORAGE_DATAFAB is not set
# CONFIG_USB_STORAGE_FREECOM is not set
# CONFIG_USB_STORAGE_ISD200 is not set
# CONFIG_USB_STORAGE_USBAT is not set
# CONFIG_USB_STORAGE_SDDR09 is not set
# CONFIG_USB_STORAGE_SDDR55 is not set
# CONFIG_USB_STORAGE_JUMPSHOT is not set
# CONFIG_USB_STORAGE_ALAUDA is not set
# CONFIG_USB_STORAGE_ONETOUCH is not set
# CONFIG_USB_STORAGE_KARMA is not set
# CONFIG_USB_STORAGE_CYPRESS_ATACB is not set
# CONFIG_USB_STORAGE_ENE_UB6250 is not set
# CONFIG_USB_UAS is not set

CONFIG_USB_ACM=y
# CONFIG_USB_PRINTER is not set
CONFIG_USB_WDM=y
# CONFIG_USB_TMC is not set

# 无用USB外设、USBIP、其他双控制器全部关闭
# CONFIG_USB_MDC800 is not set
# CONFIG_USB_MICROTEK is not set
# CONFIG_USBIP_CORE is not set
# CONFIG_USB_CDNS_SUPPORT is not set
# CONFIG_USB_MUSB_HDRC is not set

# USB网络、串口、PPP协议
CONFIG_USB_USBNET=y
CONFIG_USB_NET_CDCETHER=y
CONFIG_USB_NET_RNDIS_HOST=y
CONFIG_USB_NET_CDC_NCM=y
CONFIG_USB_SERIAL=y
CONFIG_USB_SERIAL_CONSOLE=y
CONFIG_USB_SERIAL_GENERIC=y
CONFIG_USB_SERIAL_OPTION=y
CONFIG_PPP=y
CONFIG_PPP_BSDCOMP=y
CONFIG_PPP_DEFLATE=y
CONFIG_PPP_FILTER=y
CONFIG_PPP_MPPE=y
CONFIG_PPP_MULTILINK=y
CONFIG_PPP_ASYNC=y
CONFIG_PPP_SYNC_TTY=y

# =================================================================
# 📦 模块支持
# =================================================================
CONFIG_MODULES=y
CONFIG_MODVERSIONS=y
CONFIG_MODULE_UNLOAD=y

# 适配内核定稿三路串口
CONFIG_SERIAL_8250_NR_UARTS=8
CONFIG_SERIAL_8250_EXTENDED=y

# 红外接收器硬件驱动
CONFIG_IR_GPIO_CIR=y

# 关闭无用USB HID外设节省内核体积
# CONFIG_USB_KEYBOARD is not set
# CONFIG_USB_MOUSE is not set
# CONFIG_USB_HID is not set

# =================================================================
# 📦 olddefconfig生成
# =================================================================
CONFIG_COMPILE_TEST=n
CONFIG_WERROR=n
CONFIG_LOCALVERSION=""
CONFIG_BUILD_SALT=""
CONFIG_DEFAULT_INIT=""
CONFIG_DEFAULT_HOSTNAME="(none)"
CONFIG_USELIB=n
CONFIG_HZ_PERIODIC=n
CONFIG_BPF_SYSCALL=n
CONFIG_BPF_JIT=n
CONFIG_PREEMPT_NONE=y
CONFIG_PREEMPT_VOLUNTARY=n
CONFIG_PREEMPT=n
CONFIG_PREEMPT_DYNAMIC=n
CONFIG_VIRT_CPU_ACCOUNTING_GEN=n
CONFIG_RCU_EXPERT=n
CONFIG_IKCONFIG=n
CONFIG_IKHEADERS=n
CONFIG_LOG_CPU_MAX_BUF_SHIFT=12
CONFIG_UTS_NS=y
CONFIG_TIME_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_SCHED_AUTOGROUP=n
CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y
CONFIG_CC_OPTIMIZE_FOR_SIZE=n
CONFIG_KALLSYMS_UNCOMPRESSED=n
CONFIG_EXPERT=n
CONFIG_KALLSYMS_SELFTEST=n
CONFIG_KEXEC=n
CONFIG_KEXEC_SIG=n
CONFIG_ARCH_ACTIONS=n
CONFIG_ARCH_AIROHA=n
CONFIG_ARCH_SUNXI=n
CONFIG_ARCH_ALPINE=n
CONFIG_ARCH_APPLE=n
CONFIG_ARCH_BCM=n
CONFIG_ARCH_BERLIN=n
CONFIG_ARCH_BITMAIN=n
CONFIG_ARCH_EXYNOS=n
CONFIG_ARCH_SPARX5=n
CONFIG_ARCH_K3=n
CONFIG_ARCH_LG1K=n
CONFIG_ARCH_HISI=n
CONFIG_ARCH_KEEMBAY=n
CONFIG_ARCH_MEDIATEK=n
CONFIG_ARCH_MESON=n
CONFIG_ARCH_MVEBU=n
CONFIG_ARCH_NXP=n
CONFIG_ARCH_MA35=n
CONFIG_ARCH_NPCM=n
CONFIG_ARCH_PENSANDO=n
CONFIG_ARCH_QCOM=n
CONFIG_ARCH_REALTEK=n
CONFIG_ARCH_RENESAS=n
CONFIG_ARCH_SEATTLE=n
CONFIG_ARCH_INTEL_SOCFPGA=n
CONFIG_ARCH_STM32=n
CONFIG_ARCH_SYNQUACER=n
CONFIG_ARCH_TEGRA=n
CONFIG_ARCH_SPRD=n
CONFIG_ARCH_THUNDER=n
CONFIG_ARCH_THUNDER2=n
CONFIG_ARCH_UNIPHIER=n
CONFIG_ARCH_VEXPRESS=n
CONFIG_ARCH_VISCONTI=n
CONFIG_ARCH_XGENE=n
CONFIG_ARCH_ZYNQMP=n
CONFIG_AMPERE_ERRATUM_AC03_CPU_38=y
CONFIG_ARM64_ERRATUM_1542419=n
CONFIG_ARM64_ERRATUM_1508412=y
CONFIG_ARM64_ERRATUM_2457168=y
CONFIG_ARM64_ERRATUM_2645198=y
CONFIG_ARM64_ERRATUM_2966298=y
CONFIG_ARM64_ERRATUM_3194386=y
CONFIG_ARM64_ERRATUM_4118414=y
CONFIG_CAVIUM_ERRATUM_22375=y
CONFIG_CAVIUM_ERRATUM_23154=y
CONFIG_CAVIUM_ERRATUM_27456=y
CONFIG_CAVIUM_ERRATUM_30115=y
CONFIG_CAVIUM_TX2_ERRATUM_219=y
CONFIG_FUJITSU_ERRATUM_010001=y
CONFIG_HISILICON_ERRATUM_161600802=y
CONFIG_HISILICON_ERRATUM_162100801=y
CONFIG_QCOM_FALKOR_ERRATUM_1003=y
CONFIG_QCOM_FALKOR_ERRATUM_1009=y
CONFIG_QCOM_QDF2400_ERRATUM_0065=y
CONFIG_QCOM_FALKOR_ERRATUM_E1041=y
CONFIG_NVIDIA_CARMEL_CNP_ERRATUM=y
CONFIG_SOCIONEXT_SYNQUACER_PREITS=y
CONFIG_ARM64_16K_PAGES=n
CONFIG_ARM64_64K_PAGES=n
CONFIG_ARM64_VA_BITS_52=n
CONFIG_CPU_BIG_ENDIAN=n
CONFIG_SCHED_CLUSTER=n
CONFIG_SCHED_SMT=n
CONFIG_NUMA=n
CONFIG_HZ_100=n
CONFIG_HZ_250=y
CONFIG_HZ_300=n
CONFIG_HZ_1000=n
CONFIG_PARAVIRT=n
CONFIG_PARAVIRT_TIME_ACCOUNTING=n
CONFIG_ARM64_SW_TTBR0_PAN=n
CONFIG_COMPAT=n
CONFIG_ARM64_PAN=y
CONFIG_ARM64_USE_LSE_ATOMICS=y
CONFIG_ARM64_PMEM=n
CONFIG_ARM64_CNP=y
CONFIG_ARM64_AMU_EXTN=y
CONFIG_ARM64_BTI=y
CONFIG_ARM64_E0PD=y
CONFIG_ARM64_EPAN=y
CONFIG_ARM64_POE=y
CONFIG_ARM64_PSEUDO_NMI=n
CONFIG_RANDOMIZE_BASE=n
CONFIG_CMDLINE=""
CONFIG_EFI=y
CONFIG_COMPRESSED_INSTALL=n
CONFIG_DMI=y
CONFIG_SUSPEND=y
CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE=n
CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE=n
CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND=n
CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE=n
CONFIG_ACPI=n
CONFIG_KPROBES=n
CONFIG_STATIC_KEYS_SELFTEST=n
CONFIG_SECCOMP=y
CONFIG_LTO_NONE=y
CONFIG_PAGE_SIZE_4KB=y
CONFIG_RANDOMIZE_KSTACK_OFFSET_DEFAULT=n
CONFIG_RELR=y
CONFIG_MODULE_FORCE_LOAD=n
CONFIG_MODULE_FORCE_UNLOAD=n
CONFIG_MODULE_UNLOAD_TAINT_TRACKING=n
CONFIG_MODULE_SRCVERSION_ALL=n
CONFIG_MODULE_SIG=n
CONFIG_MODULE_COMPRESS=n
CONFIG_MODULE_ALLOW_MISSING_NAMESPACE_IMPORTS=n
CONFIG_MODPROBE_PATH="/sbin/modprobe"
CONFIG_TRIM_UNUSED_KSYMS=n
CONFIG_MODULE_STRIPPED=n
CONFIG_BLOCK_LEGACY_AUTOLOAD=y
CONFIG_BLK_DEV_WRITE_MOUNTED=y
CONFIG_BLK_DEV_ZONED=n
CONFIG_BLK_WBT=n
CONFIG_BLK_SED_OPAL=n
CONFIG_BLK_INLINE_ENCRYPTION=n
CONFIG_BLOCK_NOTIFIERS=n
CONFIG_ACORN_PARTITION=n
CONFIG_AIX_PARTITION=n
CONFIG_OSF_PARTITION=n
CONFIG_AMIGA_PARTITION=n
CONFIG_ATARI_PARTITION=n
CONFIG_MAC_PARTITION=n
CONFIG_MSDOS_PARTITION=y
CONFIG_BSD_DISKLABEL=n
CONFIG_MINIX_SUBPARTITION=n
CONFIG_SOLARIS_X86_PARTITION=n
CONFIG_UNIXWARE_DISKLABEL=n
CONFIG_LDM_PARTITION=n
CONFIG_SGI_PARTITION=n
CONFIG_ULTRIX_PARTITION=n
CONFIG_SUN_PARTITION=n
CONFIG_KARMA_PARTITION=n
CONFIG_EFI_PARTITION=y
CONFIG_SYSV68_PARTITION=n
CONFIG_CMDLINE_PARTITION=n
CONFIG_OF_PARTITION=n
CONFIG_MQ_IOSCHED_KYBER=y
CONFIG_IOSCHED_BFQ=y
CONFIG_BINFMT_ELF=y
CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS=y
CONFIG_BINFMT_SCRIPT=y
CONFIG_BINFMT_MISC=n
CONFIG_SLAB_MERGE_DEFAULT=y
CONFIG_SLAB_FREELIST_RANDOM=n
CONFIG_SLAB_FREELIST_HARDENED=n
CONFIG_SLAB_BUCKETS=n
CONFIG_SLUB_STATS=n
CONFIG_SLUB_CPU_PARTIAL=y
CONFIG_RANDOM_KMALLOC_CACHES=n
CONFIG_SHUFFLE_PAGE_ALLOCATOR=n
CONFIG_COMPAT_BRK=y
CONFIG_MEMORY_HOTPLUG=n
CONFIG_PAGE_REPORTING=n
CONFIG_PCP_BATCH_SCALE_MAX=5
CONFIG_DEFAULT_MMAP_MIN_ADDR=4096
CONFIG_MEMORY_FAILURE=n
CONFIG_READ_ONLY_THP_FOR_FS=n
CONFIG_DEFERRED_STRUCT_PAGE_INIT=n
CONFIG_IDLE_PAGE_TRACKING=n
CONFIG_PERCPU_STATS=n
CONFIG_DMAPOOL_TEST=n
CONFIG_ANON_VMA_NAME=n
CONFIG_USERFAULTFD=n
CONFIG_LRU_GEN=n
CONFIG_DAMON=n
CONFIG_PACKET=n
CONFIG_UNIX=n
CONFIG_TLS=n
CONFIG_XFRM_USER=n
CONFIG_NET_KEY=n
CONFIG_IP_MULTICAST=n
CONFIG_IP_ADVANCED_ROUTER=n
CONFIG_IP_PNP=n
CONFIG_NET_IPIP=n
CONFIG_NET_IPGRE_DEMUX=n
CONFIG_SYN_COOKIES=n
CONFIG_NET_IPVTI=n
CONFIG_NET_UDP_TUNNEL=n
CONFIG_NET_FOU=n
CONFIG_NET_FOU_IP_TUNNELS=n
CONFIG_INET_AH=n
CONFIG_INET_ESP=n
CONFIG_INET_IPCOMP=n
CONFIG_INET_DIAG=y
CONFIG_INET_UDP_DIAG=n
CONFIG_INET_RAW_DIAG=n
CONFIG_INET_DIAG_DESTROY=n
CONFIG_TCP_CONG_BIC=m
CONFIG_TCP_CONG_CUBIC=y
CONFIG_TCP_CONG_WESTWOOD=m
CONFIG_TCP_CONG_HTCP=m
CONFIG_TCP_CONG_HSTCP=n
CONFIG_TCP_CONG_HYBLA=n
CONFIG_TCP_CONG_VEGAS=n
CONFIG_TCP_CONG_NV=n
CONFIG_TCP_CONG_SCALABLE=n
CONFIG_TCP_CONG_LP=n
CONFIG_TCP_CONG_VENO=n
CONFIG_TCP_CONG_YEAH=n
CONFIG_TCP_CONG_ILLINOIS=n
CONFIG_TCP_CONG_DCTCP=n
CONFIG_TCP_CONG_CDG=n
CONFIG_DEFAULT_CUBIC=n
CONFIG_DEFAULT_RENO=n
CONFIG_TCP_AO=n
CONFIG_TCP_MD5SIG=n
CONFIG_IPV6_OPTIMISTIC_DAD=n
CONFIG_INET6_AH=n
CONFIG_INET6_ESP=n
CONFIG_INET6_IPCOMP=n
CONFIG_IPV6_MIP6=n
CONFIG_IPV6_VTI=n
CONFIG_IPV6_SIT_6RD=n
CONFIG_IPV6_TUNNEL=n
CONFIG_IPV6_MULTIPLE_TABLES=n
CONFIG_IPV6_MROUTE=n
CONFIG_IPV6_SEG6_LWTUNNEL=n
CONFIG_IPV6_SEG6_HMAC=n
CONFIG_IPV6_RPL_LWTUNNEL=n
CONFIG_IPV6_IOAM6_LWTUNNEL=n
CONFIG_MPTCP=n
CONFIG_NETWORK_SECMARK=n
CONFIG_NETWORK_PHY_TIMESTAMPING=n
CONFIG_NETFILTER=n
CONFIG_IP_DCCP=n
CONFIG_IP_SCTP=n
CONFIG_RDS=n
CONFIG_TIPC=n
CONFIG_ATM=n
CONFIG_L2TP=n
CONFIG_VLAN_8021Q=n
CONFIG_LLC2=n
CONFIG_ATALK=n
CONFIG_X25=n
CONFIG_LAPB=n
CONFIG_PHONET=n
CONFIG_6LOWPAN=n
CONFIG_IEEE802154=n
CONFIG_NET_SCH_HTB=n
CONFIG_NET_SCH_HFSC=n
CONFIG_NET_SCH_PRIO=n
CONFIG_NET_SCH_MULTIQ=n
CONFIG_NET_SCH_RED=n
CONFIG_NET_SCH_SFB=n
CONFIG_NET_SCH_SFQ=n
CONFIG_NET_SCH_TEQL=n
CONFIG_NET_SCH_TBF=n
CONFIG_NET_SCH_CBS=n
CONFIG_NET_SCH_ETF=n
CONFIG_NET_SCH_TAPRIO=n
CONFIG_NET_SCH_GRED=n
CONFIG_NET_SCH_NETEM=n
CONFIG_NET_SCH_DRR=n
CONFIG_NET_SCH_MQPRIO=n
CONFIG_NET_SCH_SKBPRIO=n
CONFIG_NET_SCH_CHOKE=n
CONFIG_NET_SCH_QFQ=n
CONFIG_NET_SCH_CODEL=n
CONFIG_NET_SCH_FQ_CODEL=n
CONFIG_NET_SCH_CAKE=n
CONFIG_NET_SCH_HHF=n
CONFIG_NET_SCH_PIE=n
CONFIG_NET_SCH_PLUG=n
CONFIG_NET_SCH_ETS=n
CONFIG_NET_SCH_DEFAULT=n
CONFIG_NET_CLS_BASIC=n
CONFIG_NET_CLS_ROUTE4=n
CONFIG_NET_CLS_FW=n
CONFIG_NET_CLS_U32=n
CONFIG_NET_CLS_FLOW=n
CONFIG_NET_CLS_BPF=n
CONFIG_NET_CLS_FLOWER=n
CONFIG_NET_CLS_MATCHALL=n
CONFIG_NET_EMATCH=n
CONFIG_NET_CLS_ACT=n
CONFIG_DCB=n
CONFIG_DNS_RESOLVER=m
CONFIG_BATMAN_ADV=n
CONFIG_OPENVSWITCH=n
CONFIG_VSOCKETS=n
CONFIG_NETLINK_DIAG=n
CONFIG_MPLS=n
CONFIG_NET_NSH=n
CONFIG_HSR=n
CONFIG_NET_SWITCHDEV=n
CONFIG_NET_L3_MASTER_DEV=n
CONFIG_QRTR=n
CONFIG_NET_NCSI=n
CONFIG_PCPU_DEV_REFCNT=y
CONFIG_MAX_SKB_FRAGS=17
CONFIG_BQL=y
CONFIG_NET_PKTGEN=n
CONFIG_HAMRADIO=n
CONFIG_BT_LE_L2CAP_ECRED=y
CONFIG_BT_MSFTEXT=n
CONFIG_BT_AOSPEXT=n
CONFIG_BT_FEATURE_DEBUG=n
CONFIG_BT_HCIBCM203X=n
CONFIG_BT_HCIBPA10X=n
CONFIG_BT_HCIBFUSB=n
CONFIG_BT_HCIVHCI=n
CONFIG_BT_MRVL=n
CONFIG_BT_MTKSDIO=n
CONFIG_BT_MTKUART=n
CONFIG_BT_NXPUART=n
CONFIG_AF_RXRPC=n
CONFIG_AF_KCM=n
CONFIG_MCTP=n
CONFIG_RFKILL_FULL=n
CONFIG_NET_9P=n
CONFIG_CAIF=n
CONFIG_CEPH_LIB=n
CONFIG_NFC=n
CONFIG_PSAMPLE=n
CONFIG_NET_IFE=n
CONFIG_LWTUNNEL=n
CONFIG_PAGE_POOL_STATS=n
CONFIG_FAILOVER=n
CONFIG_ETHTOOL_NETLINK=y
CONFIG_PCCARD=n
CONFIG_TEST_ASYNC_DRIVER_PROBE=n
CONFIG_DMA_FENCE_TRACE=n
CONFIG_FW_DEVLINK_SYNC_STATE_TIMEOUT=n
CONFIG_MOXTET=n
CONFIG_VEXPRESS_CONFIG=n
CONFIG_MHI_BUS=n
CONFIG_MHI_BUS_EP=n
CONFIG_CONNECTOR=n
CONFIG_IMX_SCMI_BBM_EXT=n
CONFIG_ARM_SDE_INTERFACE=n
CONFIG_DMIID=y
CONFIG_DMI_SYSFS=n
CONFIG_SYSFB_SIMPLEFB=n
CONFIG_ARM_FFA_TRANSPORT=n
CONFIG_GOOGLE_FIRMWARE=n
CONFIG_EFI_ZBOOT=n
CONFIG_EFI_ARMSTUB_DTB_LOADER=y
CONFIG_EFI_BOOTLOADER_CONTROL=n
CONFIG_EFI_CAPSULE_LOADER=n
CONFIG_EFI_TEST=n
CONFIG_RESET_ATTACK_MITIGATION=n
CONFIG_EFI_DISABLE_PCI_DMA=n
CONFIG_EFI_DISABLE_RUNTIME=n
CONFIG_EFI_COCO_SECRET=n
CONFIG_ARM_PSCI_CHECKER=n
CONFIG_ARM_SMCCC_SOC_ID=y
CONFIG_MTD_ROOTFS_ROOT_DEV=y
CONFIG_MTD_SPLIT_FIRMWARE_NAME="firmware"
CONFIG_MTD_SPLIT_SQUASHFS_ROOT=n
CONFIG_MTD_SPLIT_BCM63XX_FW=n
CONFIG_MTD_SPLIT_BCM_WFI_FW=n
CONFIG_MTD_SPLIT_SEAMA_FW=n
CONFIG_MTD_SPLIT_WRGG_FW=n
CONFIG_MTD_SPLIT_UIMAGE_FW=n
CONFIG_MTD_SPLIT_FIT_FW=n
CONFIG_MTD_SPLIT_LZMA_FW=n
CONFIG_MTD_SPLIT_TPLINK_FW=n
CONFIG_MTD_SPLIT_TRX_FW=n
CONFIG_MTD_SPLIT_BRNIMAGE_FW=n
CONFIG_MTD_SPLIT_EVA_FW=n
CONFIG_MTD_SPLIT_MINOR_FW=n
CONFIG_MTD_SPLIT_JIMAGE_FW=n
CONFIG_MTD_SPLIT_ELF_FW=n
CONFIG_MTD_SPLIT_H3C_VFS=n
CONFIG_MTD_SPLIT_SEIL_FW=n
CONFIG_MTD_SPLIT_MSTC_BOOT=n
CONFIG_MTD_SPLIT_OPENWRT_PROLOG=n
CONFIG_MTD_TESTS=n
CONFIG_MTD_AFS_PARTS=n
CONFIG_MTD_REDBOOT_PARTS=n
CONFIG_MTD_ROUTERBOOT_PARTS=n
CONFIG_INFTL=n
CONFIG_RFD_FTL=n
CONFIG_SSFDC=n
CONFIG_SM_FTL=n
CONFIG_MTD_OOPS=n
CONFIG_MTD_PARTITIONED_MASTER=n
CONFIG_MTD_JEDECPROBE=n
CONFIG_MTD_RAM=n
CONFIG_MTD_ROM=n
CONFIG_MTD_ABSENT=n
CONFIG_MTD_PLATRAM=n
CONFIG_MTD_DATAFLASH=n
CONFIG_MTD_MCHP23K256=n
CONFIG_MTD_MCHP48L640=n
CONFIG_MTD_SST25L=n
CONFIG_MTD_SLRAM=n
CONFIG_MTD_PHRAM=n
CONFIG_MTD_MTDRAM=n
CONFIG_MTD_BLOCK2MTD=n
CONFIG_MTD_DOCG3=n
CONFIG_MTD_ONENAND=n
CONFIG_MTD_RAW_NAND=n
CONFIG_MTD_SPI_NAND=n
CONFIG_MTD_NAND_ECC_SW_HAMMING=n
CONFIG_MTD_NAND_ECC_SW_BCH=n
CONFIG_MTD_NAND_MTK_BMT=n
CONFIG_MTD_NAND_ECC_MXIC=n
CONFIG_MTD_LPDDR=n
CONFIG_MTD_SPI_NOR_SWP_DISABLE=n
CONFIG_MTD_SPI_NOR_SWP_DISABLE_ON_VOLATILE=y
CONFIG_MTD_SPI_NOR_SWP_KEEP=n
CONFIG_MTD_UBI=n
CONFIG_MTD_HYPERBUS=n
CONFIG_MTD_VIRT_CONCAT=n
CONFIG_OF_UNITTEST=n
CONFIG_NVME_FC=n
CONFIG_NVME_TCP=n
CONFIG_AD525X_DPOT=n
CONFIG_DUMMY_IRQ=n
CONFIG_RPMB=n
CONFIG_ICS932S401=n
CONFIG_ENCLOSURE_SERVICES=n
CONFIG_APDS9802ALS=n
CONFIG_ISL29003=n
CONFIG_ISL29020=n
CONFIG_SENSORS_TSL2550=n
CONFIG_SENSORS_BH1770=n
CONFIG_SENSORS_APDS990X=n
CONFIG_HMC6352=n
CONFIG_DS1682=n
CONFIG_LATTICE_ECP3_CONFIG=n
CONFIG_XILINX_SDFEC=n
CONFIG_HISI_HIKEY_USB=n
CONFIG_OPEN_DICE=n
CONFIG_VCPU_STALL_DETECTOR=n
CONFIG_C2PORT=n
CONFIG_EEPROM_AT25=n
CONFIG_EEPROM_MAX6875=n
CONFIG_EEPROM_93CX6=n
CONFIG_EEPROM_93XX46=n
CONFIG_EEPROM_IDT_89HPESX=n
CONFIG_EEPROM_EE1004=n
CONFIG_TI_ST=n
CONFIG_SENSORS_LIS3_SPI=n
CONFIG_SENSORS_LIS3_I2C=n
CONFIG_ALTERA_STAPL=n
CONFIG_ECHO=n
CONFIG_MISC_RTSX_USB=n
CONFIG_UACCE=n
CONFIG_PVPANIC=n
CONFIG_NET_CORE=y
CONFIG_BONDING=n
CONFIG_DUMMY=n
CONFIG_WIREGUARD=n
CONFIG_EQUALIZER=n
CONFIG_NET_TEAM=n
CONFIG_MACVLAN=n
CONFIG_IPVLAN=n
CONFIG_VXLAN=n
CONFIG_GENEVE=n
CONFIG_BAREUDP=n
CONFIG_GTP=n
CONFIG_PFCP=n
CONFIG_MACSEC=n
CONFIG_NETCONSOLE=n
CONFIG_TUN=n
CONFIG_TUN_VNET_CROSS_LE=n
CONFIG_VETH=n
CONFIG_NLMON=n
CONFIG_ETHERNET=y
CONFIG_NET_VENDOR_ALACRITECH=y
CONFIG_ALTERA_TSE=n
CONFIG_NET_VENDOR_AMAZON=y
CONFIG_NET_VENDOR_AMD=y
CONFIG_AMD_XGBE=n
CONFIG_NET_VENDOR_AQUANTIA=y
CONFIG_NET_VENDOR_ARC=y
CONFIG_NET_VENDOR_ASIX=y
CONFIG_SPI_AX88796C=n
CONFIG_NET_VENDOR_BROADCOM=y
CONFIG_B44=n
CONFIG_BCMGENET=n
CONFIG_SYSTEMPORT=n
CONFIG_NET_VENDOR_CADENCE=y
CONFIG_MACB=n
CONFIG_NET_VENDOR_CAVIUM=y
CONFIG_NET_VENDOR_CORTINA=y
CONFIG_GEMINI_ETHERNET=n
CONFIG_NET_VENDOR_DAVICOM=y
CONFIG_DM9051=n
CONFIG_DNET=n
CONFIG_NET_VENDOR_ENGLEDER=y
CONFIG_TSNEP=n
CONFIG_NET_VENDOR_EZCHIP=y
CONFIG_EZCHIP_NPS_MANAGEMENT_ENET=n
CONFIG_NET_VENDOR_FUNGIBLE=y
CONFIG_NET_VENDOR_GOOGLE=y
CONFIG_NET_VENDOR_HISILICON=y
CONFIG_HIX5HD2_GMAC=n
CONFIG_HISI_FEMAC=n
CONFIG_HIP04_ETH=n
CONFIG_HNS_DSAF=n
CONFIG_HNS_ENET=n
CONFIG_NET_VENDOR_HUAWEI=y
CONFIG_NET_VENDOR_I825XX=y
CONFIG_NET_VENDOR_INTEL=y
CONFIG_NET_VENDOR_ADI=y
CONFIG_NET_VENDOR_LITEX=y
CONFIG_LITEX_LITEETH=n
CONFIG_NET_VENDOR_MARVELL=y
CONFIG_MVMDIO=n
CONFIG_NET_VENDOR_MELLANOX=y
CONFIG_MLXSW_CORE=n
CONFIG_MLXFW=n
CONFIG_NET_VENDOR_META=y
CONFIG_NET_VENDOR_MICREL=y
CONFIG_KS8842=n
CONFIG_KS8851=n
CONFIG_KS8851_MLL=n
CONFIG_NET_VENDOR_MICROCHIP=y
CONFIG_ENC28J60=n
CONFIG_ENCX24J600=n
CONFIG_LAN865X=n
CONFIG_VCAP=n
CONFIG_NET_VENDOR_MICROSEMI=y
CONFIG_NET_VENDOR_MICROSOFT=y
CONFIG_NET_VENDOR_NI=y
CONFIG_NI_XGE_MANAGEMENT_ENET=n
CONFIG_NET_VENDOR_NATSEMI=y
CONFIG_NET_VENDOR_NETRONOME=y
CONFIG_NET_VENDOR_8390=y
CONFIG_ETHOC=n
CONFIG_OA_TC6=n
CONFIG_NET_VENDOR_PENSANDO=y
CONFIG_NET_VENDOR_QUALCOMM=y
CONFIG_QCA7000_SPI=n
CONFIG_QCA7000_UART=n
CONFIG_QCOM_EMAC=n
CONFIG_RMNET=n
CONFIG_NET_VENDOR_RENESAS=y
CONFIG_NET_VENDOR_ROCKER=y
CONFIG_NET_VENDOR_SAMSUNG=y
CONFIG_SXGBE_ETH=n
CONFIG_NET_VENDOR_SEEQ=y
CONFIG_NET_VENDOR_SOLARFLARE=y
CONFIG_NET_VENDOR_SMSC=y
CONFIG_SMC91X=n
CONFIG_SMSC911X=n
CONFIG_NET_VENDOR_SOCIONEXT=y
CONFIG_STMMAC_SELFTESTS=n
CONFIG_DWMAC_INTEL_PLAT=n
CONFIG_NET_VENDOR_SYNOPSYS=y
CONFIG_DWC_XLGMAC=n
CONFIG_NET_VENDOR_VERTEXCOM=y
CONFIG_MSE102X=n
CONFIG_NET_VENDOR_VIA=y
CONFIG_VIA_VELOCITY=n
CONFIG_NET_VENDOR_WANGXUN=y
CONFIG_NET_VENDOR_WIZNET=y
CONFIG_WIZNET_W5100=n
CONFIG_WIZNET_W5300=n
CONFIG_NET_VENDOR_XILINX=y
CONFIG_XILINX_EMACLITE=n
CONFIG_XILINX_LL_TEMAC=n
CONFIG_SFP=n
CONFIG_SWCONFIG=n
CONFIG_ADM6996_PHY=n
CONFIG_AR8216_PHY=n
CONFIG_IP17XX_PHY=n
CONFIG_PSB6970_PHY=n
CONFIG_RTL8306_PHY=n
CONFIG_RTL8366_SMI=n
CONFIG_AS21XXX_PHY=n
CONFIG_AIR_EN8811H_PHY=n
CONFIG_AMD_PHY=n
CONFIG_ADIN_PHY=n
CONFIG_ADIN1100_PHY=n
CONFIG_AQUANTIA_PHY=n
CONFIG_BROADCOM_PHY=n
CONFIG_BCM54140_PHY=n
CONFIG_BCM7XXX_PHY=n
CONFIG_BCM84881_PHY=n
CONFIG_BCM87XX_PHY=n
CONFIG_CICADA_PHY=n
CONFIG_CORTINA_PHY=n
CONFIG_DAVICOM_PHY=n
CONFIG_ICPLUS_PHY=n
CONFIG_LXT_PHY=n
CONFIG_INTEL_XWAY_PHY=n
CONFIG_LSI_ET1011C_PHY=n
CONFIG_MARVELL_PHY=n
CONFIG_MARVELL_10G_PHY=n
CONFIG_MARVELL_88Q2XXX_PHY=n
CONFIG_MARVELL_88X2222_PHY=n
CONFIG_MAXLINEAR_GPHY=n
CONFIG_MICROCHIP_T1S_PHY=n
CONFIG_MICROCHIP_PHY=n
CONFIG_MICROCHIP_T1_PHY=n
CONFIG_MICROSEMI_PHY=n
CONFIG_NATIONAL_PHY=n
CONFIG_NXP_CBTX_PHY=n
CONFIG_NXP_C45_TJA11XX_PHY=n
CONFIG_NCN26000_PHY=n
CONFIG_AT803X_PHY=n
CONFIG_QCA83XX_PHY=n
CONFIG_QCA808X_PHY=n
CONFIG_QCA807X_PHY=n
CONFIG_QSEMI_PHY=n
CONFIG_RTL8261N_PHY=n
CONFIG_RENESAS_PHY=n
CONFIG_SMSC_PHY=n
CONFIG_STE10XP=n
CONFIG_TERANETICS_PHY=n
CONFIG_DP83822_PHY=n
CONFIG_DP83TC811_PHY=n
CONFIG_DP83848_PHY=n
CONFIG_DP83867_PHY=n
CONFIG_DP83869_PHY=n
CONFIG_DP83TD510_PHY=n
CONFIG_DP83TG720_PHY=n
CONFIG_VITESSE_PHY=n
CONFIG_XILINX_GMII2RGMII=n
CONFIG_PSE_CONTROLLER=n
CONFIG_MDIO_BITBANG=n
CONFIG_MDIO_BCM_UNIMAC=n
CONFIG_MDIO_HISI_FEMAC=n
CONFIG_MDIO_MVUSB=n
CONFIG_MDIO_MSCC_MIIM=n
CONFIG_MDIO_OCTEON=n
CONFIG_MDIO_IPQ4019=n
CONFIG_MDIO_IPQ8064=n
CONFIG_MDIO_BUS_MUX_MULTIPLEXER=n
CONFIG_PCS_MTK_USXGMII=n
CONFIG_PPPOE=n
CONFIG_SLIP=n
CONFIG_USB_NET_DRIVERS=y
CONFIG_USB_CATC=n
CONFIG_USB_KAWETH=n
CONFIG_USB_PEGASUS=n
CONFIG_USB_RTL8150=n
CONFIG_USB_RTL8152=n
CONFIG_USB_LAN78XX=n
CONFIG_USB_NET_AX8817X=y
CONFIG_USB_NET_AX88179_178A=y
CONFIG_USB_NET_CDC_EEM=n
CONFIG_USB_NET_HUAWEI_CDC_NCM=n
CONFIG_USB_NET_CDC_MBIM=n
CONFIG_USB_NET_DM9601=n
CONFIG_USB_NET_SR9700=n
CONFIG_USB_NET_SR9800=n
CONFIG_USB_NET_SMSC75XX=n
CONFIG_USB_NET_SMSC95XX=n
CONFIG_USB_NET_GL620A=n
CONFIG_USB_NET_NET1080=y
CONFIG_USB_NET_PLUSB=n
CONFIG_USB_NET_MCS7830=n
CONFIG_USB_NET_CDC_SUBSET=y
CONFIG_USB_ALI_M5632=n
CONFIG_USB_AN2720=n
CONFIG_USB_BELKIN=y
CONFIG_USB_ARMLINUX=y
CONFIG_USB_EPSON2888=n
CONFIG_USB_KC2190=n
CONFIG_USB_NET_ZAURUS=y
CONFIG_USB_NET_CX82310_ETH=n
CONFIG_USB_NET_KALMIA=n
CONFIG_USB_NET_QMI_WWAN=n
CONFIG_USB_HSO=n
CONFIG_USB_NET_INT51X1=n
CONFIG_USB_IPHETH=n
CONFIG_USB_SIERRA_NET=n
CONFIG_USB_VL600=n
CONFIG_USB_NET_CH9200=n
CONFIG_USB_NET_AQC111=n
CONFIG_WAN=n
CONFIG_WWAN=n
CONFIG_NET_FAILOVER=n
CONFIG_ISDN=n
CONFIG_INPUT_SPARSEKMAP=n
CONFIG_INPUT_MOUSEDEV=n
CONFIG_INPUT_JOYDEV=n
CONFIG_INPUT_EVBUG=n
CONFIG_KEYBOARD_ADP5588=n
CONFIG_KEYBOARD_ADP5589=n
CONFIG_KEYBOARD_ATKBD=y
CONFIG_KEYBOARD_QT1050=n
CONFIG_KEYBOARD_QT1070=n
CONFIG_KEYBOARD_QT2160=n
CONFIG_KEYBOARD_DLINK_DIR685=n
CONFIG_KEYBOARD_LKKBD=n
CONFIG_KEYBOARD_GPIO_POLLED=n
CONFIG_KEYBOARD_TCA6416=n
CONFIG_KEYBOARD_TCA8418=n
CONFIG_KEYBOARD_MATRIX=n
CONFIG_KEYBOARD_LM8333=n
CONFIG_KEYBOARD_MAX7359=n
CONFIG_KEYBOARD_MPR121=n
CONFIG_KEYBOARD_NEWTON=n
CONFIG_KEYBOARD_OPENCORES=n
CONFIG_KEYBOARD_PINEPHONE=n
CONFIG_KEYBOARD_SAMSUNG=n
CONFIG_KEYBOARD_STOWAWAY=n
CONFIG_KEYBOARD_SUNKBD=n
CONFIG_KEYBOARD_OMAP4=n
CONFIG_KEYBOARD_XTKBD=n
CONFIG_KEYBOARD_CAP11XX=n
CONFIG_KEYBOARD_BCM=n
CONFIG_KEYBOARD_CYPRESS_SF=n
CONFIG_INPUT_MOUSE=y
CONFIG_MOUSE_PS2=y
CONFIG_MOUSE_PS2_ELANTECH=n
CONFIG_MOUSE_PS2_SENTELIC=n
CONFIG_MOUSE_PS2_TOUCHKIT=n
CONFIG_MOUSE_SERIAL=n
CONFIG_MOUSE_APPLETOUCH=n
CONFIG_MOUSE_BCM5974=n
CONFIG_MOUSE_CYAPA=n
CONFIG_MOUSE_ELAN_I2C=n
CONFIG_MOUSE_VSXXXAA=n
CONFIG_MOUSE_GPIO=n
CONFIG_MOUSE_SYNAPTICS_I2C=n
CONFIG_MOUSE_SYNAPTICS_USB=n
CONFIG_INPUT_JOYSTICK=n
CONFIG_INPUT_TABLET=n
CONFIG_INPUT_TOUCHSCREEN=n
CONFIG_INPUT_MISC=n
CONFIG_RMI4_CORE=n
CONFIG_SERIO_SERPORT=y
CONFIG_SERIO_RAW=n
CONFIG_SERIO_ALTERA_PS2=n
CONFIG_SERIO_PS2MULT=n
CONFIG_SERIO_ARC_PS2=n
CONFIG_SERIO_APBPS2=n
CONFIG_SERIO_GPIO_PS2=n
CONFIG_USERIO=n
CONFIG_GAMEPORT=n
CONFIG_LEGACY_PTYS=y
CONFIG_LEGACY_PTY_COUNT=256
CONFIG_LEGACY_TIOCSTI=y
CONFIG_LDISC_AUTOLOAD=y
CONFIG_SERIAL_8250_16550A_VARIANTS=y
CONFIG_SERIAL_8250_FINTEK=n
CONFIG_SERIAL_8250_MANY_PORTS=n
CONFIG_SERIAL_8250_DETECT_IRQ=n
CONFIG_SERIAL_8250_RSA=n
CONFIG_SERIAL_8250_RT288X=n
CONFIG_SERIAL_AMBA_PL010=n
CONFIG_SERIAL_EARLYCON_SEMIHOST=n
CONFIG_SERIAL_MAX3100=n
CONFIG_SERIAL_MAX310X=n
CONFIG_SERIAL_UARTLITE=n
CONFIG_SERIAL_SIFIVE=n
CONFIG_SERIAL_SCCNXP=n
CONFIG_SERIAL_SC16IS7XX=n
CONFIG_SERIAL_ALTERA_JTAGUART=n
CONFIG_SERIAL_ALTERA_UART=n
CONFIG_SERIAL_XILINX_PS_UART=n
CONFIG_SERIAL_ARC=n
CONFIG_SERIAL_FSL_LPUART=n
CONFIG_SERIAL_FSL_LINFLEXUART=n
CONFIG_SERIAL_CONEXANT_DIGICOLOR=n
CONFIG_SERIAL_SPRD=n
CONFIG_SERIAL_NONSTANDARD=n
CONFIG_N_GSM=n
CONFIG_NULL_TTY=n
CONFIG_HVC_DCC=n
CONFIG_IPMI_HANDLER=n
CONFIG_HW_RANDOM_TIMERIOMEM=n
CONFIG_HW_RANDOM_BA431=n
CONFIG_HW_RANDOM_CCTRNG=n
CONFIG_HW_RANDOM_XIPHERA=n
CONFIG_HW_RANDOM_ARM_SMCCC_TRNG=y
CONFIG_TCG_TPM=n
CONFIG_XILLYBUS=n
CONFIG_XILLYUSB=n
CONFIG_I2C_ARB_GPIO_CHALLENGE=n
CONFIG_I2C_MUX_GPIO=n
CONFIG_I2C_MUX_GPMUX=n
CONFIG_I2C_MUX_LTC4306=n
CONFIG_I2C_MUX_PCA9541=n
CONFIG_I2C_MUX_PCA954x=n
CONFIG_I2C_MUX_PINCTRL=n
CONFIG_I2C_MUX_REG=n
CONFIG_I2C_DEMUX_PINCTRL=n
CONFIG_I2C_MUX_MLXCPLD=n
CONFIG_I2C_CADENCE=n
CONFIG_I2C_CBUS_GPIO=n
CONFIG_I2C_DESIGNWARE_CORE=n
CONFIG_I2C_EMEV2=n
CONFIG_I2C_GPIO=n
CONFIG_I2C_HISI=n
CONFIG_I2C_NOMADIK=n
CONFIG_I2C_OCORES=n
CONFIG_I2C_PCA_PLATFORM=n
CONFIG_I2C_SIMTEC=n
CONFIG_I2C_XILINX=n
CONFIG_I2C_DIOLAN_U2C=n
CONFIG_I2C_CP2615=n
CONFIG_I2C_ROBOTFUZZ_OSIF=n
CONFIG_I2C_TAOS_EVM=n
CONFIG_I2C_TINY_USB=n
CONFIG_I2C_VIRTIO=n
CONFIG_I2C_STUB=n
CONFIG_I2C_SLAVE=n
CONFIG_I2C_DEBUG_CORE=n
CONFIG_I2C_DEBUG_ALGO=n
CONFIG_I2C_DEBUG_BUS=n
CONFIG_I3C=n
CONFIG_SPI_ALTERA=n
CONFIG_SPI_AXI_SPI_ENGINE=n
CONFIG_SPI_CADENCE=n
CONFIG_SPI_CADENCE_QUADSPI=n
CONFIG_SPI_CADENCE_XSPI=n
CONFIG_SPI_CH341=n
CONFIG_SPI_DESIGNWARE=n
CONFIG_SPI_GPIO=n
CONFIG_SPI_FSL_SPI=n
CONFIG_SPI_MICROCHIP_CORE=n
CONFIG_SPI_MICROCHIP_CORE_QSPI=n
CONFIG_SPI_OC_TINY=n
CONFIG_SPI_PL022=n
CONFIG_SPI_SC18IS602=n
CONFIG_SPI_SIFIVE=n
CONFIG_SPI_SN_F_OSPI=n
CONFIG_SPI_MXIC=n
CONFIG_SPI_XCOMM=n
CONFIG_SPI_XILINX=n
CONFIG_SPI_ZYNQMP_GQSPI=n
CONFIG_SPI_AMD=n
CONFIG_SPI_MUX=n
CONFIG_SPI_LOOPBACK_TEST=n
CONFIG_SPI_TLE62X0=n
CONFIG_SPI_SLAVE=n
CONFIG_SPMI=n
CONFIG_HSI=n
CONFIG_PPS_DEBUG=n
CONFIG_PPS_CLIENT_KTIMER=n
CONFIG_PPS_CLIENT_LDISC=n
CONFIG_PPS_CLIENT_GPIO=n
CONFIG_PTP_1588_CLOCK_KVM=y
CONFIG_PTP_1588_CLOCK_IDT82P33=n
CONFIG_PTP_1588_CLOCK_IDTCM=n
CONFIG_PTP_1588_CLOCK_FC3W=n
CONFIG_PTP_1588_CLOCK_MOCK=n
CONFIG_PINCTRL_AW9523=n
CONFIG_PINCTRL_CY8C95X0=n
CONFIG_PINCTRL_MCP23S08=n
CONFIG_PINCTRL_MICROCHIP_SGPIO=n
CONFIG_PINCTRL_OCELOT=n
CONFIG_PINCTRL_STMFX=n
CONFIG_PINCTRL_SX150X=n
CONFIG_PINCTRL_IMX_SCMI=n
CONFIG_GPIOLIB_FASTPATH_LIMIT=512
CONFIG_GPIO_CDEV_V1=y
CONFIG_GPIO_74XX_MMIO=n
CONFIG_GPIO_ALTERA=n
CONFIG_GPIO_CADENCE=n
CONFIG_GPIO_FTGPIO010=n
CONFIG_GPIO_GRGPIO=n
CONFIG_GPIO_HISI=n
CONFIG_GPIO_HLWD=n
CONFIG_GPIO_LOGICVC=n
CONFIG_GPIO_MB86S7X=n
CONFIG_GPIO_PL061=n
CONFIG_GPIO_SIFIVE=n
CONFIG_GPIO_XGENE=n
CONFIG_GPIO_XILINX=n
CONFIG_GPIO_AMD_FCH=n
CONFIG_GPIO_ADNP=n
CONFIG_GPIO_FXL6408=n
CONFIG_GPIO_DS4520=n
CONFIG_GPIO_GW_PLD=n
CONFIG_GPIO_MAX7300=n
CONFIG_GPIO_MAX732X=n
CONFIG_GPIO_PCA953X=n
CONFIG_GPIO_PCA9570=n
CONFIG_GPIO_PCF857X=n
CONFIG_GPIO_TPIC2810=n
CONFIG_GPIO_74X164=n
CONFIG_GPIO_MAX3191X=n
CONFIG_GPIO_MAX7301=n
CONFIG_GPIO_MC33880=n
CONFIG_GPIO_PISOSR=n
CONFIG_GPIO_XRA1403=n
CONFIG_GPIO_AGGREGATOR=n
CONFIG_GPIO_LATCH=n
CONFIG_GPIO_MOCKUP=n
CONFIG_GPIO_SIM=n
CONFIG_GPIO_VIRTUSER=n
CONFIG_GPIO_CASCADE=n
CONFIG_W1=n
CONFIG_POWER_RESET_GPIO=n
CONFIG_POWER_RESET_GPIO_RESTART=n
CONFIG_POWER_RESET_LTC2952=n
CONFIG_POWER_RESET_REGULATOR=n
CONFIG_POWER_RESET_RESTART=n
CONFIG_POWER_RESET_XGENE=n
CONFIG_POWER_RESET_SYSCON=n
CONFIG_POWER_RESET_SYSCON_POWEROFF=n
CONFIG_SYSCON_REBOOT_MODE=n
CONFIG_NVMEM_REBOOT_MODE=n
CONFIG_POWER_SEQUENCING=n
CONFIG_POWER_SUPPLY_DEBUG=n
CONFIG_IP5XXX_POWER=n
CONFIG_TEST_POWER=n
CONFIG_CHARGER_ADP5061=n
CONFIG_BATTERY_CW2015=n
CONFIG_BATTERY_DS2780=n
CONFIG_BATTERY_DS2781=n
CONFIG_BATTERY_DS2782=n
CONFIG_BATTERY_SAMSUNG_SDI=n
CONFIG_BATTERY_SBS=n
CONFIG_CHARGER_SBS=n
CONFIG_MANAGER_SBS=n
CONFIG_BATTERY_BQ27XXX=n
CONFIG_BATTERY_MAX17042=n
CONFIG_BATTERY_MAX1720X=n
CONFIG_CHARGER_ISP1704=n
CONFIG_CHARGER_MAX8903=n
CONFIG_CHARGER_LP8727=n
CONFIG_CHARGER_MANAGER=n
CONFIG_CHARGER_LT3651=n
CONFIG_CHARGER_LTC4162L=n
CONFIG_CHARGER_DETECTOR_MAX14656=n
CONFIG_CHARGER_MAX77976=n
CONFIG_CHARGER_BQ2415X=n
CONFIG_CHARGER_BQ24190=n
CONFIG_CHARGER_BQ24257=n
CONFIG_CHARGER_BQ24735=n
CONFIG_CHARGER_BQ2515X=n
CONFIG_CHARGER_BQ25890=n
CONFIG_CHARGER_BQ25980=n
CONFIG_CHARGER_BQ256XX=n
CONFIG_CHARGER_SMB347=n
CONFIG_BATTERY_GAUGE_LTC2941=n
CONFIG_BATTERY_GOLDFISH=n
CONFIG_BATTERY_RT5033=n
CONFIG_CHARGER_RT9455=n
CONFIG_CHARGER_RT9467=n
CONFIG_CHARGER_RT9471=n
CONFIG_CHARGER_UCS1002=n
CONFIG_CHARGER_BD99954=n
CONFIG_BATTERY_UG3105=n
CONFIG_FUEL_GAUGE_MM8013=n
CONFIG_THERMAL_NETLINK=n
CONFIG_THERMAL_STATISTICS=n
CONFIG_THERMAL_DEFAULT_GOV_FAIR_SHARE=n
CONFIG_THERMAL_DEFAULT_GOV_USER_SPACE=n
CONFIG_THERMAL_DEFAULT_GOV_POWER_ALLOCATOR=n
CONFIG_THERMAL_GOV_FAIR_SHARE=n
CONFIG_THERMAL_GOV_BANG_BANG=n
CONFIG_THERMAL_GOV_USER_SPACE=n
CONFIG_CPU_FREQ_THERMAL=y
CONFIG_THERMAL_MMIO=n
CONFIG_MFD_ADP5585=n
CONFIG_MFD_ACT8945A=n
CONFIG_MFD_AS3711=n
CONFIG_MFD_SMPRO=n
CONFIG_MFD_AS3722=n
CONFIG_PMIC_ADP5520=n
CONFIG_MFD_AAT2870_CORE=n
CONFIG_MFD_ATMEL_FLEXCOM=n
CONFIG_MFD_ATMEL_HLCDC=n
CONFIG_MFD_BCM590XX=n
CONFIG_MFD_BD9571MWV=n
CONFIG_MFD_AXP20X_I2C=n
CONFIG_MFD_CS42L43_I2C=n
CONFIG_MFD_MADERA=n
CONFIG_MFD_MAX5970=n
CONFIG_PMIC_DA903X=n
CONFIG_MFD_DA9052_SPI=n
CONFIG_MFD_DA9052_I2C=n
CONFIG_MFD_DA9055=n
CONFIG_MFD_DA9062=n
CONFIG_MFD_DA9063=n
CONFIG_MFD_DA9150=n
CONFIG_MFD_DLN2=n
CONFIG_MFD_GATEWORKS_GSC=n
CONFIG_MFD_MC13XXX_SPI=n
CONFIG_MFD_MC13XXX_I2C=n
CONFIG_MFD_MP2629=n
CONFIG_MFD_HI6421_PMIC=n
CONFIG_MFD_IQS62X=n
CONFIG_MFD_KEMPLD=n
CONFIG_MFD_88PM800=n
CONFIG_MFD_88PM805=n
CONFIG_MFD_88PM860X=n
CONFIG_MFD_88PM886_PMIC=n
CONFIG_MFD_MAX14577=n
CONFIG_MFD_MAX77541=n
CONFIG_MFD_MAX77620=n
CONFIG_MFD_MAX77650=n
CONFIG_MFD_MAX77686=n
CONFIG_MFD_MAX77693=n
CONFIG_MFD_MAX77714=n
CONFIG_MFD_MAX77843=n
CONFIG_MFD_MAX8907=n
CONFIG_MFD_MAX8925=n
CONFIG_MFD_MAX8997=n
CONFIG_MFD_MAX8998=n
CONFIG_MFD_MT6360=n
CONFIG_MFD_MT6370=n
CONFIG_MFD_MT6397=n
CONFIG_MFD_MENF21BMC=n
CONFIG_MFD_OCELOT=n
CONFIG_EZX_PCAP=n
CONFIG_MFD_CPCAP=n
CONFIG_MFD_VIPERBOARD=n
CONFIG_MFD_NTXEC=n
CONFIG_MFD_RETU=n
CONFIG_MFD_PCF50633=n
CONFIG_MFD_SY7636A=n
CONFIG_MFD_RT4831=n
CONFIG_MFD_RT5033=n
CONFIG_MFD_RT5120=n
CONFIG_MFD_RC5T583=n
CONFIG_MFD_RN5T618=n
CONFIG_MFD_SEC_CORE=n
CONFIG_MFD_SI476X_CORE=n
CONFIG_MFD_SM501=n
CONFIG_MFD_SKY81452=n
CONFIG_MFD_STMPE=n
CONFIG_MFD_LP3943=n
CONFIG_MFD_LP8788=n
CONFIG_MFD_TI_LMU=n
CONFIG_MFD_PALMAS=n
CONFIG_TPS6105X=n
CONFIG_TPS65010=n
CONFIG_TPS6507X=n
CONFIG_MFD_TPS65086=n
CONFIG_MFD_TPS65090=n
CONFIG_MFD_TPS65217=n
CONFIG_MFD_TI_LP873X=n
CONFIG_MFD_TI_LP87565=n
CONFIG_MFD_TPS65218=n
CONFIG_MFD_TPS65219=n
CONFIG_MFD_TPS6586X=n
CONFIG_MFD_TPS65910=n
CONFIG_MFD_TPS65912_I2C=n
CONFIG_MFD_TPS65912_SPI=n
CONFIG_MFD_TPS6594_I2C=n
CONFIG_MFD_TPS6594_SPI=n
CONFIG_TWL4030_CORE=n
CONFIG_TWL6040_CORE=n
CONFIG_MFD_WL1273_CORE=n
CONFIG_MFD_LM3533=n
CONFIG_MFD_TC3589X=n
CONFIG_MFD_TQMX86=n
CONFIG_MFD_LOCHNAGAR=n
CONFIG_MFD_ARIZONA_I2C=n
CONFIG_MFD_ARIZONA_SPI=n
CONFIG_MFD_WM8400=n
CONFIG_MFD_WM831X_I2C=n
CONFIG_MFD_WM831X_SPI=n
CONFIG_MFD_WM8350_I2C=n
CONFIG_MFD_WM8994=n
CONFIG_MFD_ROHM_BD718XX=n
CONFIG_MFD_ROHM_BD71828=n
CONFIG_MFD_ROHM_BD957XMUF=n
CONFIG_MFD_ROHM_BD96801=n
CONFIG_MFD_STPMIC1=n
CONFIG_MFD_STMFX=n
CONFIG_MFD_ATC260X_I2C=n
CONFIG_MFD_QCOM_PM8008=n
CONFIG_MFD_CS40L50_I2C=n
CONFIG_MFD_CS40L50_SPI=n
CONFIG_MFD_INTEL_M10_BMC_SPI=n
CONFIG_MFD_RSMU_I2C=n
CONFIG_MFD_RSMU_SPI=n
CONFIG_REGULATOR_DEBUG=n
CONFIG_REGULATOR_VIRTUAL_CONSUMER=n
CONFIG_REGULATOR_USERSPACE_CONSUMER=n
CONFIG_REGULATOR_NETLINK_EVENTS=n
CONFIG_REGULATOR_88PG86X=n
CONFIG_REGULATOR_ACT8865=n
CONFIG_REGULATOR_AD5398=n
CONFIG_REGULATOR_AW37503=n
CONFIG_REGULATOR_DA9121=n
CONFIG_REGULATOR_DA9210=n
CONFIG_REGULATOR_DA9211=n
CONFIG_REGULATOR_FAN53880=n
CONFIG_REGULATOR_ISL9305=n
CONFIG_REGULATOR_ISL6271A=n
CONFIG_REGULATOR_LP3971=n
CONFIG_REGULATOR_LP3972=n
CONFIG_REGULATOR_LP872X=n
CONFIG_REGULATOR_LP8755=n
CONFIG_REGULATOR_LTC3589=n
CONFIG_REGULATOR_LTC3676=n
CONFIG_REGULATOR_MAX1586=n
CONFIG_REGULATOR_MAX77503=n
CONFIG_REGULATOR_MAX77857=n
CONFIG_REGULATOR_MAX8649=n
CONFIG_REGULATOR_MAX8660=n
CONFIG_REGULATOR_MAX8893=n
CONFIG_REGULATOR_MAX8952=n
CONFIG_REGULATOR_MAX8973=n
CONFIG_REGULATOR_MAX20086=n
CONFIG_REGULATOR_MAX20411=n
CONFIG_REGULATOR_MAX77826=n
CONFIG_REGULATOR_MCP16502=n
CONFIG_REGULATOR_MP5416=n
CONFIG_REGULATOR_MP8859=n
CONFIG_REGULATOR_MP886X=n
CONFIG_REGULATOR_MPQ7920=n
CONFIG_REGULATOR_MT6311=n
CONFIG_REGULATOR_PCA9450=n
CONFIG_REGULATOR_PF8X00=n
CONFIG_REGULATOR_PFUZE100=n
CONFIG_REGULATOR_PV88060=n
CONFIG_REGULATOR_PV88080=n
CONFIG_REGULATOR_PV88090=n
CONFIG_REGULATOR_RAA215300=n
CONFIG_REGULATOR_RASPBERRYPI_TOUCHSCREEN_ATTINY=n
CONFIG_REGULATOR_RT4801=n
CONFIG_REGULATOR_RT4803=n
CONFIG_REGULATOR_RT5190A=n
CONFIG_REGULATOR_RT5739=n
CONFIG_REGULATOR_RT5759=n
CONFIG_REGULATOR_RT6160=n
CONFIG_REGULATOR_RT6190=n
CONFIG_REGULATOR_RT6245=n
CONFIG_REGULATOR_RTQ2134=n
CONFIG_REGULATOR_RTMV20=n
CONFIG_REGULATOR_RTQ6752=n
CONFIG_REGULATOR_RTQ2208=n
CONFIG_REGULATOR_SLG51000=n
CONFIG_REGULATOR_SY8106A=n
CONFIG_REGULATOR_SY8824X=n
CONFIG_REGULATOR_SY8827N=n
CONFIG_REGULATOR_TPS51632=n
CONFIG_REGULATOR_TPS62360=n
CONFIG_REGULATOR_TPS6286X=n
CONFIG_REGULATOR_TPS6287X=n
CONFIG_REGULATOR_TPS65023=n
CONFIG_REGULATOR_TPS6507X=n
CONFIG_REGULATOR_TPS65132=n
CONFIG_REGULATOR_TPS6524X=n
CONFIG_REGULATOR_VCTRL=n
CONFIG_RC_CORE=n
CONFIG_MEDIA_CEC_SUPPORT=n
CONFIG_MEDIA_SUPPORT_FILTER=y
CONFIG_MEDIA_SUBDRV_AUTOSELECT=y
CONFIG_MEDIA_ANALOG_TV_SUPPORT=n
CONFIG_MEDIA_DIGITAL_TV_SUPPORT=n
CONFIG_MEDIA_RADIO_SUPPORT=n
CONFIG_MEDIA_SDR_SUPPORT=n
CONFIG_MEDIA_TEST_SUPPORT=n
CONFIG_VIDEO_ADV_DEBUG=n
CONFIG_VIDEO_FIXED_MINOR_RANGES=n
CONFIG_MEDIA_USB_SUPPORT=n
CONFIG_MEDIA_PLATFORM_DRIVERS=y
CONFIG_V4L_PLATFORM_DRIVERS=n
CONFIG_VIDEO_MEM2MEM_DEINTERLACE=n
CONFIG_VIDEO_CADENCE_CSI2RX=n
CONFIG_VIDEO_CADENCE_CSI2TX=n
CONFIG_VIDEO_CAMERA_SENSOR=y
CONFIG_VIDEO_ALVIUM_CSI2=n
CONFIG_VIDEO_AR0521=n
CONFIG_VIDEO_GC0308=n
CONFIG_VIDEO_GC05A2=n
CONFIG_VIDEO_GC08A3=n
CONFIG_VIDEO_GC2145=n
CONFIG_VIDEO_HI556=n
CONFIG_VIDEO_HI846=n
CONFIG_VIDEO_HI847=n
CONFIG_VIDEO_IMX208=n
CONFIG_VIDEO_IMX214=n
CONFIG_VIDEO_IMX219=n
CONFIG_VIDEO_IMX258=n
CONFIG_VIDEO_IMX274=n
CONFIG_VIDEO_IMX283=n
CONFIG_VIDEO_IMX290=n
CONFIG_VIDEO_IMX296=n
CONFIG_VIDEO_IMX319=n
CONFIG_VIDEO_IMX334=n
CONFIG_VIDEO_IMX335=n
CONFIG_VIDEO_IMX355=n
CONFIG_VIDEO_IMX412=n
CONFIG_VIDEO_IMX415=n
CONFIG_VIDEO_MT9M001=n
CONFIG_VIDEO_MT9M111=n
CONFIG_VIDEO_MT9M114=n
CONFIG_VIDEO_MT9P031=n
CONFIG_VIDEO_MT9T112=n
CONFIG_VIDEO_MT9V011=n
CONFIG_VIDEO_MT9V032=n
CONFIG_VIDEO_MT9V111=n
CONFIG_VIDEO_OG01A1B=n
CONFIG_VIDEO_OV01A10=n
CONFIG_VIDEO_OV02A10=n
CONFIG_VIDEO_OV08D10=n
CONFIG_VIDEO_OV08X40=n
CONFIG_VIDEO_OV13858=n
CONFIG_VIDEO_OV13B10=n
CONFIG_VIDEO_OV2640=n
CONFIG_VIDEO_OV2659=n
CONFIG_VIDEO_OV2680=n
CONFIG_VIDEO_OV2685=n
CONFIG_VIDEO_OV4689=n
CONFIG_VIDEO_OV5640=n
CONFIG_VIDEO_OV5645=n
CONFIG_VIDEO_OV5647=n
CONFIG_VIDEO_OV5648=n
CONFIG_VIDEO_OV5670=n
CONFIG_VIDEO_OV5675=n
CONFIG_VIDEO_OV5693=n
CONFIG_VIDEO_OV5695=n
CONFIG_VIDEO_OV64A40=n
CONFIG_VIDEO_OV6650=n
CONFIG_VIDEO_OV7251=n
CONFIG_VIDEO_OV7640=n
CONFIG_VIDEO_OV7670=n
CONFIG_VIDEO_OV772X=n
CONFIG_VIDEO_OV7740=n
CONFIG_VIDEO_OV8856=n
CONFIG_VIDEO_OV8858=n
CONFIG_VIDEO_OV8865=n
CONFIG_VIDEO_OV9282=n
CONFIG_VIDEO_OV9640=n
CONFIG_VIDEO_OV9650=n
CONFIG_VIDEO_RDACM20=n
CONFIG_VIDEO_RDACM21=n
CONFIG_VIDEO_RJ54N1=n
CONFIG_VIDEO_S5C73M3=n
CONFIG_VIDEO_S5K5BAF=n
CONFIG_VIDEO_S5K6A3=n
CONFIG_VIDEO_VGXY61=n
CONFIG_VIDEO_CCS=n
CONFIG_VIDEO_ET8EK8=n
CONFIG_VIDEO_THP7312=n
CONFIG_VIDEO_AD5820=n
CONFIG_VIDEO_AK7375=n
CONFIG_VIDEO_DW9714=n
CONFIG_VIDEO_DW9719=n
CONFIG_VIDEO_DW9768=n
CONFIG_VIDEO_DW9807_VCM=n
CONFIG_VIDEO_ADP1653=n
CONFIG_VIDEO_LM3560=n
CONFIG_VIDEO_LM3646=n
CONFIG_VIDEO_DS90UB913=n
CONFIG_VIDEO_DS90UB953=n
CONFIG_VIDEO_DS90UB960=n
CONFIG_VIDEO_MAX96714=n
CONFIG_VIDEO_MAX96717=n
CONFIG_VIDEO_GS1662=n
CONFIG_AUXDISPLAY=n
CONFIG_DRM_DEBUG_MM=n
CONFIG_DRM_PANIC=n
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_DRM_FBDEV_OVERALLOC=100
CONFIG_DRM_LOAD_EDID_FIRMWARE=n
CONFIG_DRM_I2C_CH7006=n
CONFIG_DRM_I2C_SIL164=n
CONFIG_DRM_I2C_NXP_TDA998X=n
CONFIG_DRM_I2C_NXP_TDA9950=n
CONFIG_DRM_HDLCD=n
CONFIG_DRM_MALI_DISPLAY=n
CONFIG_DRM_KOMEDA=n
CONFIG_DRM_VGEM=n
CONFIG_DRM_VKMS=n
CONFIG_DRM_ROCKCHIP=n
CONFIG_DRM_UDL=n
CONFIG_DRM_PANEL_ABT_Y030XX067A=n
CONFIG_DRM_PANEL_ARM_VERSATILE=n
CONFIG_DRM_PANEL_AUO_A030JTN01=n
CONFIG_DRM_PANEL_LVDS=n
CONFIG_DRM_PANEL_ILITEK_IL9322=n
CONFIG_DRM_PANEL_ILITEK_ILI9341=n
CONFIG_DRM_PANEL_INNOLUX_EJ030NA=n
CONFIG_DRM_PANEL_LG_LB035Q02=n
CONFIG_DRM_PANEL_LG_LG4573=n
CONFIG_DRM_PANEL_NEC_NL8048HL11=n
CONFIG_DRM_PANEL_NEWVISION_NV3052C=n
CONFIG_DRM_PANEL_NOVATEK_NT39016=n
CONFIG_DRM_PANEL_OLIMEX_LCD_OLINUXINO=n
CONFIG_DRM_PANEL_ORISETECH_OTA5601A=n
CONFIG_DRM_PANEL_SAMSUNG_S6E88A0_AMS452EF01=n
CONFIG_DRM_PANEL_SAMSUNG_ATNA33XC20=n
CONFIG_DRM_PANEL_SAMSUNG_DB7430=n
CONFIG_DRM_PANEL_SAMSUNG_LD9040=n
CONFIG_DRM_PANEL_SAMSUNG_S6D27A1=n
CONFIG_DRM_PANEL_SAMSUNG_S6D7AA0=n
CONFIG_DRM_PANEL_SAMSUNG_S6E63M0=n
CONFIG_DRM_PANEL_SAMSUNG_S6E8AA0=n
CONFIG_DRM_PANEL_SEIKO_43WVF1G=n
CONFIG_DRM_PANEL_SHARP_LS037V7DW01=n
CONFIG_DRM_PANEL_SITRONIX_ST7701=n
CONFIG_DRM_PANEL_SONY_ACX565AKM=n
CONFIG_DRM_PANEL_EDP=n
CONFIG_DRM_PANEL_SIMPLE=n
CONFIG_DRM_PANEL_TPO_TD028TTEC1=n
CONFIG_DRM_PANEL_TPO_TD043MTEA1=n
CONFIG_DRM_PANEL_TPO_TPG110=n
CONFIG_DRM_PANEL_WIDECHIPS_WS2401=n
CONFIG_DRM_CHIPONE_ICN6211=n
CONFIG_DRM_CHRONTEL_CH7033=n
CONFIG_DRM_DISPLAY_CONNECTOR=n
CONFIG_DRM_ITE_IT6505=n
CONFIG_DRM_LONTIUM_LT8912B=n
CONFIG_DRM_LONTIUM_LT9211=n
CONFIG_DRM_LONTIUM_LT9611=n
CONFIG_DRM_LONTIUM_LT9611UXC=n
CONFIG_DRM_ITE_IT66121=n
CONFIG_DRM_LVDS_CODEC=n
CONFIG_DRM_MEGACHIPS_STDPXXXX_GE_B850V3_FW=n
CONFIG_DRM_NWL_MIPI_DSI=n
CONFIG_DRM_NXP_PTN3460=n
CONFIG_DRM_PARADE_PS8622=n
CONFIG_DRM_PARADE_PS8640=n
CONFIG_DRM_SAMSUNG_DSIM=n
CONFIG_DRM_SIL_SII8620=n
CONFIG_DRM_SII902X=n
CONFIG_DRM_SII9234=n
CONFIG_DRM_SIMPLE_BRIDGE=n
CONFIG_DRM_THINE_THC63LVD1024=n
CONFIG_DRM_TOSHIBA_TC358762=n
CONFIG_DRM_TOSHIBA_TC358764=n
CONFIG_DRM_TOSHIBA_TC358767=n
CONFIG_DRM_TOSHIBA_TC358768=n
CONFIG_DRM_TOSHIBA_TC358775=n
CONFIG_DRM_TI_DLPC3433=n
CONFIG_DRM_TI_TFP410=n
CONFIG_DRM_TI_SN65DSI83=n
CONFIG_DRM_TI_SN65DSI86=n
CONFIG_DRM_TI_TPD12S015=n
CONFIG_DRM_ANALOGIX_ANX6345=n
CONFIG_DRM_ANALOGIX_ANX78XX=n
CONFIG_DRM_ANALOGIX_ANX7625=n
CONFIG_DRM_I2C_ADV7511=n
CONFIG_DRM_CDNS_DSI=n
CONFIG_DRM_CDNS_MHDP8546=n
CONFIG_DRM_ETNAVIV=n
CONFIG_DRM_HISI_KIRIN=n
CONFIG_DRM_LOGICVC=n
CONFIG_DRM_ARCPGU=n
CONFIG_DRM_GM12U320=n
CONFIG_DRM_PANEL_MIPI_DBI=n
CONFIG_TINYDRM_HX8357D=n
CONFIG_TINYDRM_ILI9163=n
CONFIG_TINYDRM_ILI9225=n
CONFIG_TINYDRM_ILI9341=n
CONFIG_TINYDRM_ILI9486=n
CONFIG_TINYDRM_MI0283QT=n
CONFIG_TINYDRM_REPAPER=n
CONFIG_TINYDRM_ST7586=n
CONFIG_TINYDRM_ST7735R=n
CONFIG_DRM_PL111=n
CONFIG_DRM_LIMA=n
CONFIG_DRM_PANFROST=n
CONFIG_DRM_PANTHOR=n
CONFIG_DRM_TIDSS=n
CONFIG_DRM_GUD=n
CONFIG_DRM_SSD130X=n
CONFIG_DRM_POWERVR=n
CONFIG_FB_EFI=n
CONFIG_FB_OPENCORES=n
CONFIG_FB_S1D13XXX=n
CONFIG_FB_SMSCUFX=n
CONFIG_FB_UDL=n
CONFIG_FB_IBM_GXT4500=n
CONFIG_FB_VIRTUAL=n
CONFIG_FB_METRONOME=n
CONFIG_FB_SIMPLE=n
CONFIG_FB_SSD1307=n
CONFIG_FIRMWARE_EDID=n
CONFIG_FB_DEVICE=y
CONFIG_FB_FOREIGN_ENDIAN=n
CONFIG_FB_TILEBLITTING=n
CONFIG_LCD_CLASS_DEVICE=n
CONFIG_BACKLIGHT_KTD253=n
CONFIG_BACKLIGHT_KTD2801=n
CONFIG_BACKLIGHT_KTZ8866=n
CONFIG_BACKLIGHT_QCOM_WLED=n
CONFIG_BACKLIGHT_ADP8860=n
CONFIG_BACKLIGHT_ADP8870=n
CONFIG_BACKLIGHT_LM3509=n
CONFIG_BACKLIGHT_LM3630A=n
CONFIG_BACKLIGHT_LM3639=n
CONFIG_BACKLIGHT_LP855X=n
CONFIG_BACKLIGHT_MP3309C=n
CONFIG_BACKLIGHT_LV5207LP=n
CONFIG_BACKLIGHT_BD6107=n
CONFIG_BACKLIGHT_ARCXCNN=n
CONFIG_DUMMY_CONSOLE_COLUMNS=80
CONFIG_DUMMY_CONSOLE_ROWS=25
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_FRAMEBUFFER_CONSOLE_LEGACY_ACCELERATION=n
CONFIG_FRAMEBUFFER_CONSOLE_ROTATION=n
CONFIG_FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER=n
CONFIG_LOGO=n
CONFIG_DRM_ACCEL=n
CONFIG_HID_SUPPORT=y
CONFIG_HID_BATTERY_STRENGTH=n
CONFIG_HIDRAW=n
CONFIG_UHID=n
CONFIG_HID_GENERIC=y
CONFIG_HID_A4TECH=y
CONFIG_HID_ACRUX=n
CONFIG_HID_AUREAL=n
CONFIG_HID_BELKIN=y
CONFIG_HID_CHERRY=y
CONFIG_HID_COUGAR=n
CONFIG_HID_MACALLY=n
CONFIG_HID_CMEDIA=n
CONFIG_HID_CYPRESS=y
CONFIG_HID_DRAGONRISE=n
CONFIG_HID_EMS_FF=n
CONFIG_HID_ELECOM=n
CONFIG_HID_EVISION=n
CONFIG_HID_EZKEY=y
CONFIG_HID_GEMBIRD=n
CONFIG_HID_GFRM=n
CONFIG_HID_GLORIOUS=n
CONFIG_HID_GOODIX_SPI=n
CONFIG_HID_GOOGLE_STADIA_FF=n
CONFIG_HID_VIVALDI=n
CONFIG_HID_KEYTOUCH=n
CONFIG_HID_KYE=n
CONFIG_HID_WALTOP=n
CONFIG_HID_VIEWSONIC=n
CONFIG_HID_VRC2=n
CONFIG_HID_XIAOMI=n
CONFIG_HID_GYRATION=n
CONFIG_HID_ICADE=n
CONFIG_HID_ITE=y
CONFIG_HID_JABRA=n
CONFIG_HID_TWINHAN=n
CONFIG_HID_KENSINGTON=y
CONFIG_HID_LCPOWER=n
CONFIG_HID_LENOVO=n
CONFIG_HID_MAGICMOUSE=n
CONFIG_HID_MALTRON=n
CONFIG_HID_MAYFLASH=n
CONFIG_HID_REDRAGON=y
CONFIG_HID_MICROSOFT=y
CONFIG_HID_MONTEREY=y
CONFIG_HID_MULTITOUCH=n
CONFIG_HID_NTI=n
CONFIG_HID_ORTEK=n
CONFIG_HID_PANTHERLORD=n
CONFIG_HID_PETALYNX=n
CONFIG_HID_PICOLCD=n
CONFIG_HID_PLANTRONICS=n
CONFIG_HID_PXRC=n
CONFIG_HID_RAZER=n
CONFIG_HID_PRIMAX=n
CONFIG_HID_SAITEK=n
CONFIG_HID_SEMITEK=n
CONFIG_HID_SPEEDLINK=n
CONFIG_HID_STEAM=n
CONFIG_HID_SUNPLUS=n
CONFIG_HID_RMI=n
CONFIG_HID_GREENASIA=n
CONFIG_HID_SMARTJOYPLUS=n
CONFIG_HID_TIVO=n
CONFIG_HID_TOPSEED=n
CONFIG_HID_TOPRE=n
CONFIG_HID_UDRAW_PS3=n
CONFIG_HID_XINMO=n
CONFIG_HID_ZEROPLUS=n
CONFIG_HID_ZYDACRON=n
CONFIG_HID_SENSOR_HUB=n
CONFIG_HID_ALPS=n
CONFIG_HID_PID=n
CONFIG_I2C_HID=y
CONFIG_I2C_HID_OF=n
CONFIG_I2C_HID_OF_ELAN=n
CONFIG_I2C_HID_OF_GOODIX=n
CONFIG_USB_DWC2=n
CONFIG_USB_CHIPIDEA=n
CONFIG_USB_ISP1760=n
CONFIG_USB_SERIAL_SIMPLE=n
CONFIG_USB_SERIAL_AIRCABLE=n
CONFIG_USB_SERIAL_ARK3116=n
CONFIG_USB_SERIAL_BELKIN=n
CONFIG_USB_SERIAL_CH341=n
CONFIG_USB_SERIAL_CH348=n
CONFIG_USB_SERIAL_WHITEHEAT=n
CONFIG_USB_SERIAL_DIGI_ACCELEPORT=n
CONFIG_USB_SERIAL_CP210X=n
CONFIG_USB_SERIAL_CYPRESS_M8=n
CONFIG_USB_SERIAL_EMPEG=n
CONFIG_USB_SERIAL_FTDI_SIO=n
CONFIG_USB_SERIAL_VISOR=n
CONFIG_USB_SERIAL_IPAQ=n
CONFIG_USB_SERIAL_IR=n
CONFIG_USB_SERIAL_EDGEPORT=n
CONFIG_USB_SERIAL_EDGEPORT_TI=n
CONFIG_USB_SERIAL_F81232=n
CONFIG_USB_SERIAL_F8153X=n
CONFIG_USB_SERIAL_GARMIN=n
CONFIG_USB_SERIAL_IPW=n
CONFIG_USB_SERIAL_IUU=n
CONFIG_USB_SERIAL_KEYSPAN_PDA=n
CONFIG_USB_SERIAL_KEYSPAN=n
CONFIG_USB_SERIAL_KLSI=n
CONFIG_USB_SERIAL_KOBIL_SCT=n
CONFIG_USB_SERIAL_MCT_U232=n
CONFIG_USB_SERIAL_METRO=n
CONFIG_USB_SERIAL_MOS7720=n
CONFIG_USB_SERIAL_MOS7840=n
CONFIG_USB_SERIAL_MXUPORT=n
CONFIG_USB_SERIAL_NAVMAN=n
CONFIG_USB_SERIAL_PL2303=n
CONFIG_USB_SERIAL_OTI6858=n
CONFIG_USB_SERIAL_QCAUX=n
CONFIG_USB_SERIAL_QUALCOMM=n
CONFIG_USB_SERIAL_SPCP8X5=n
CONFIG_USB_SERIAL_SAFE=n
CONFIG_USB_SERIAL_SIERRAWIRELESS=n
CONFIG_USB_SERIAL_SYMBOL=n
CONFIG_USB_SERIAL_TI=n
CONFIG_USB_SERIAL_CYBERJACK=n
CONFIG_USB_SERIAL_OMNINET=n
CONFIG_USB_SERIAL_OPTICON=n
CONFIG_USB_SERIAL_XSENS_MT=n
CONFIG_USB_SERIAL_WISHBONE=n
CONFIG_USB_SERIAL_SSU100=n
CONFIG_USB_SERIAL_QT2=n
CONFIG_USB_SERIAL_UPD78F0730=n
CONFIG_USB_SERIAL_XR=n
CONFIG_USB_SERIAL_DEBUG=n
CONFIG_USB_EMI62=n
CONFIG_USB_EMI26=n
CONFIG_USB_ADUTUX=n
CONFIG_USB_SEVSEG=n
CONFIG_USB_LEGOTOWER=n
CONFIG_USB_LCD=n
CONFIG_USB_CYPRESS_CY7C63=n
CONFIG_USB_CYTHERM=n
CONFIG_USB_IDMOUSE=n
CONFIG_USB_APPLEDISPLAY=n
CONFIG_APPLE_MFI_FASTCHARGE=n
CONFIG_USB_LD=n
CONFIG_USB_TRANCEVIBRATOR=n
CONFIG_USB_IOWARRIOR=n
CONFIG_USB_TEST=n
CONFIG_USB_EHSET_TEST_FIXTURE=n
CONFIG_USB_ISIGHTFW=n
CONFIG_USB_YUREX=n
CONFIG_USB_EZUSB_FX2=n
CONFIG_USB_HUB_USB251XB=n
CONFIG_USB_HSIC_USB3503=n
CONFIG_USB_HSIC_USB4604=n
CONFIG_USB_LINK_LAYER_TEST=n
CONFIG_USB_CHAOSKEY=n
CONFIG_USB_ONBOARD_DEV=n
CONFIG_USB_GPIO_VBUS=n
CONFIG_USB_ISP1301=n
CONFIG_USB_GADGET_DEBUG_FILES=n
CONFIG_USB_GADGET_VBUS_DRAW=2
CONFIG_USB_GADGET_STORAGE_NUM_BUFFERS=2
CONFIG_USB_GR_UDC=n
CONFIG_USB_R8A66597=n
CONFIG_USB_PXA27X=n
CONFIG_USB_MV_UDC=n
CONFIG_USB_MV_U3D=n
CONFIG_USB_SNP_UDC_PLAT=n
CONFIG_USB_M66592=n
CONFIG_USB_BDC_UDC=n
CONFIG_USB_NET2272=n
CONFIG_USB_GADGET_XILINX=n
CONFIG_USB_MAX3420_UDC=n
CONFIG_USB_DUMMY_HCD=n
CONFIG_USB_CONFIGFS=n
CONFIG_USB_ZERO=n
CONFIG_USB_ETH=n
CONFIG_USB_G_NCM=n
CONFIG_USB_GADGETFS=n
CONFIG_USB_FUNCTIONFS=n
CONFIG_USB_MASS_STORAGE=n
CONFIG_USB_G_SERIAL=n
CONFIG_USB_G_PRINTER=n
CONFIG_USB_CDC_COMPOSITE=n
CONFIG_USB_G_ACM_MS=n
CONFIG_USB_G_MULTI=n
CONFIG_USB_G_HID=n
CONFIG_USB_G_DBGP=n
CONFIG_USB_G_WEBCAM=n
CONFIG_USB_RAW_GADGET=n
CONFIG_TYPEC_UCSI=n
CONFIG_TYPEC_DP_ALTMODE=n
CONFIG_PWRSEQ_EMMC=y
CONFIG_PWRSEQ_SIMPLE=y
CONFIG_SDIO_UART=n
CONFIG_MMC_TEST=n
CONFIG_MMC_DEBUG=n
CONFIG_MMC_ARMMMCI=n
CONFIG_MMC_SDHCI_OF_AT91=n
CONFIG_MMC_SDHCI_CADENCE=n
CONFIG_MMC_SDHCI_F_SDH30=n
CONFIG_MMC_SDHCI_MILBEAUT=n
CONFIG_MMC_SPI=n
CONFIG_MMC_VUB300=n
CONFIG_MMC_USHC=n
CONFIG_MMC_USDHI6ROL0=n
CONFIG_MMC_HSQ=n
CONFIG_MMC_MTK=n
CONFIG_MMC_SDHCI_XENON=n
CONFIG_MEMSTICK=n
CONFIG_NEW_LEDS=n
CONFIG_ACCESSIBILITY=n
CONFIG_DMADEVICES_DEBUG=n
CONFIG_ALTERA_MSGDMA=n
CONFIG_AMBA_PL08X=n
CONFIG_DW_AXI_DMAC=n
CONFIG_FSL_EDMA=n
CONFIG_FSL_QDMA=n
CONFIG_INTEL_IDMA64=n
CONFIG_MV_XOR_V2=n
CONFIG_XILINX_DMA=n
CONFIG_XILINX_XDMA=n
CONFIG_XILINX_ZYNQMP_DMA=n
CONFIG_XILINX_ZYNQMP_DPDMA=n
CONFIG_AMD_QDMA=n
CONFIG_QCOM_HIDMA_MGMT=n
CONFIG_QCOM_HIDMA=n
CONFIG_DW_DMAC=n
CONFIG_SF_PDMA=n
CONFIG_ASYNC_TX_DMA=n
CONFIG_DMATEST=n
CONFIG_UDMABUF=n
CONFIG_DMABUF_MOVE_NOTIFY=n
CONFIG_DMABUF_DEBUG=n
CONFIG_DMABUF_SELFTESTS=n
CONFIG_DMABUF_HEAPS=n
CONFIG_DMABUF_SYSFS_STATS=n
CONFIG_UIO=n
CONFIG_VFIO=n
CONFIG_GOLDFISH=n
CONFIG_CHROME_PLATFORMS=n
CONFIG_MELLANOX_PLATFORM=n
CONFIG_SURFACE_PLATFORMS=y
CONFIG_MIKROTIK=n
CONFIG_CLK_ICST=n
CONFIG_CLK_SP810=n
CONFIG_LMK04832=n
CONFIG_COMMON_CLK_MAX9485=n
CONFIG_COMMON_CLK_SI5341=n
CONFIG_COMMON_CLK_SI5351=n
CONFIG_COMMON_CLK_SI514=n
CONFIG_COMMON_CLK_SI544=n
CONFIG_COMMON_CLK_SI570=n
CONFIG_COMMON_CLK_CDCE706=n
CONFIG_COMMON_CLK_CDCE925=n
CONFIG_COMMON_CLK_CS2000_CP=n
CONFIG_COMMON_CLK_AXI_CLKGEN=n
CONFIG_COMMON_CLK_XGENE=n
CONFIG_COMMON_CLK_PWM=n
CONFIG_COMMON_CLK_RS9_PCIE=n
CONFIG_COMMON_CLK_SI521XX=n
CONFIG_COMMON_CLK_VC3=n
CONFIG_COMMON_CLK_VC5=n
CONFIG_COMMON_CLK_VC7=n
CONFIG_COMMON_CLK_FIXED_MMIO=n
CONFIG_XILINX_VCU=n
CONFIG_COMMON_CLK_XLNX_CLKWZRD=n
CONFIG_FSL_ERRATUM_A008585=y
CONFIG_HISILICON_ERRATUM_161010101=y
CONFIG_ARM_TIMER_SP804=n
CONFIG_PL320_MBOX=n
CONFIG_ALTERA_MBOX=n
CONFIG_RPMSG_QCOM_GLINK_RPM=n
CONFIG_RPMSG_VIRTIO=n
CONFIG_SOUNDWIRE=n
CONFIG_QUICC_ENGINE=n
CONFIG_FSL_RCPM=n
CONFIG_LITEX_SOC_CONTROLLER=n
CONFIG_WPCM450_SOC=n
CONFIG_SOC_TI=n
CONFIG_EXTCON_FSA9480=n
CONFIG_EXTCON_GPIO=n
CONFIG_EXTCON_LC824206XA=n
CONFIG_EXTCON_MAX3355=n
CONFIG_EXTCON_PTN5150=n
CONFIG_EXTCON_RT8973A=n
CONFIG_EXTCON_SM5502=n
CONFIG_EXTCON_USB_GPIO=n
CONFIG_EXTCON_USBC_TUSB320=n
CONFIG_MEMORY=n
CONFIG_PWM_ATMEL_TCB=n
CONFIG_PWM_CLK=n
CONFIG_PWM_FSL_FTM=n
CONFIG_PWM_PCA9685=n
CONFIG_PWM_XILINX=n
CONFIG_AL_FIC=n
CONFIG_XILINX_INTC=n
CONFIG_IPACK_BUS=n
CONFIG_RESET_GPIO=n
CONFIG_RESET_TI_SYSCON=n
CONFIG_RESET_TI_TPS380X=n
CONFIG_PHY_CAN_TRANSCEIVER=n
CONFIG_BCM_KONA_USB2_PHY=n
CONFIG_PHY_CADENCE_TORRENT=n
CONFIG_PHY_CADENCE_DPHY=n
CONFIG_PHY_CADENCE_DPHY_RX=n
CONFIG_PHY_CADENCE_SIERRA=n
CONFIG_PHY_CADENCE_SALVO=n
CONFIG_PHY_PXA_28NM_HSIC=n
CONFIG_PHY_PXA_28NM_USB2=n
CONFIG_PHY_LAN966X_SERDES=n
CONFIG_PHY_MAPPHONE_MDM6600=n
CONFIG_PHY_OCELOT_SERDES=n
CONFIG_PHY_QCOM_USB_HS=n
CONFIG_PHY_QCOM_USB_HSIC=n
CONFIG_PHY_TUSB1210=n
CONFIG_POWERCAP=n
CONFIG_ANDROID_BINDER_IPC=n
CONFIG_NVMEM_LAYOUT_SL28_VPD=n
CONFIG_NVMEM_LAYOUT_ONIE_TLV=n
CONFIG_NVMEM_LAYOUT_U_BOOT_ENV=n
CONFIG_NVMEM_LAYOUT_ASCII_ENV=n
CONFIG_NVMEM_BLOCK=n
CONFIG_NVMEM_RMEM=n
CONFIG_NVMEM_U_BOOT_ENV=n
CONFIG_STM=n
CONFIG_INTEL_TH=n
CONFIG_FSI=n
CONFIG_TEE=n
CONFIG_COUNTER=n
CONFIG_VALIDATE_FS_PARSER=n
CONFIG_EXT2_FS=n
CONFIG_EXT3_FS=n
CONFIG_EXT4_USE_FOR_EXT2=y
CONFIG_EXT4_FS_POSIX_ACL=n
CONFIG_EXT4_FS_SECURITY=n
CONFIG_EXT4_DEBUG=n
CONFIG_JBD2_DEBUG=n
CONFIG_REISERFS_FS=n
CONFIG_JFS_FS=n
CONFIG_XFS_FS=n
CONFIG_GFS2_FS=n
CONFIG_OCFS2_FS=n
CONFIG_BTRFS_FS=n
CONFIG_NILFS2_FS=n
CONFIG_F2FS_STAT_FS=y
CONFIG_F2FS_FS_XATTR=y
CONFIG_F2FS_FS_POSIX_ACL=y
CONFIG_F2FS_FS_SECURITY=n
CONFIG_F2FS_CHECK_FS=n
CONFIG_F2FS_FAULT_INJECTION=n
CONFIG_F2FS_FS_COMPRESSION=n
CONFIG_F2FS_IOSTAT=y
CONFIG_BCACHEFS_FS=n
CONFIG_EXPORTFS_BLOCK_OPS=n
CONFIG_FS_ENCRYPTION=n
CONFIG_FS_VERITY=n
CONFIG_INOTIFY_USER=y
CONFIG_QUOTA_NETLINK_INTERFACE=n
CONFIG_QUOTA_DEBUG=n
CONFIG_QFMT_V1=n
CONFIG_AUTOFS_FS=n
CONFIG_FUSE_FS=n
CONFIG_OVERLAY_FS_REDIRECT_DIR=n
CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y
CONFIG_OVERLAY_FS_INDEX=n
CONFIG_OVERLAY_FS_METACOPY=n
CONFIG_OVERLAY_FS_DEBUG=n
CONFIG_NETFS_STATS=n
CONFIG_NETFS_DEBUG=n
CONFIG_FSCACHE_STATS=n
CONFIG_CACHEFILES=n
CONFIG_ISO9660_FS=n
CONFIG_UDF_FS=n
CONFIG_MSDOS_FS=n
CONFIG_NTFS3_FS=n
CONFIG_NTFS_FS=n
CONFIG_PROC_KCORE=n
CONFIG_PROC_VMCORE_DEVICE_DUMP=n
CONFIG_PROC_CHILDREN=n
CONFIG_TMPFS=n
CONFIG_EFIVAR_FS=m
CONFIG_MISC_FILESYSTEMS=y
CONFIG_ORANGEFS_FS=n
CONFIG_ADFS_FS=n
CONFIG_AFFS_FS=n
CONFIG_ECRYPT_FS=n
CONFIG_HFS_FS=n
CONFIG_HFSPLUS_FS=n
CONFIG_BEFS_FS=n
CONFIG_BFS_FS=n
CONFIG_EFS_FS=n
CONFIG_JFFS2_FS=n
CONFIG_CRAMFS=n
CONFIG_SQUASHFS_CHOICE_DECOMP_BY_MOUNT=n
CONFIG_SQUASHFS_COMPILE_DECOMP_SINGLE=y
CONFIG_SQUASHFS_COMPILE_DECOMP_MULTI=n
CONFIG_SQUASHFS_COMPILE_DECOMP_MULTI_PERCPU=n
CONFIG_SQUASHFS_ZLIB=y
CONFIG_SQUASHFS_LZ4=n
CONFIG_SQUASHFS_LZO=n
CONFIG_SQUASHFS_XZ=n
CONFIG_SQUASHFS_4K_DEVBLK_SIZE=n
CONFIG_VXFS_FS=n
CONFIG_MINIX_FS=n
CONFIG_OMFS_FS=n
CONFIG_HPFS_FS=n
CONFIG_QNX4FS_FS=n
CONFIG_QNX6FS_FS=n
CONFIG_ROMFS_FS=n
CONFIG_PSTORE=n
CONFIG_SYSV_FS=n
CONFIG_UFS_FS=n
CONFIG_EROFS_FS=n
CONFIG_NETWORK_FILESYSTEMS=y
CONFIG_NFS_FS=n
CONFIG_NFSD=n
CONFIG_CEPH_FS=n
CONFIG_CIFS_STATS2=y
CONFIG_CIFS_UPCALL=n
CONFIG_CIFS_DEBUG=y
CONFIG_CIFS_DEBUG2=n
CONFIG_CIFS_DEBUG_DUMP_KEYS=n
CONFIG_CIFS_DFS_UPCALL=n
CONFIG_CIFS_SWN_UPCALL=n
CONFIG_CIFS_FSCACHE=n
CONFIG_CIFS_COMPRESSION=n
CONFIG_SMB_SERVER=n
CONFIG_CODA_FS=n
CONFIG_AFS_FS=n
CONFIG_NLS_DEFAULT="iso8859-1"
CONFIG_NLS_CODEPAGE_437=n
CONFIG_NLS_CODEPAGE_737=n
CONFIG_NLS_CODEPAGE_775=n
CONFIG_NLS_CODEPAGE_850=n
CONFIG_NLS_CODEPAGE_852=n
CONFIG_NLS_CODEPAGE_855=n
CONFIG_NLS_CODEPAGE_857=n
CONFIG_NLS_CODEPAGE_860=n
CONFIG_NLS_CODEPAGE_861=n
CONFIG_NLS_CODEPAGE_862=n
CONFIG_NLS_CODEPAGE_863=n
CONFIG_NLS_CODEPAGE_864=n
CONFIG_NLS_CODEPAGE_865=n
CONFIG_NLS_CODEPAGE_866=n
CONFIG_NLS_CODEPAGE_869=n
CONFIG_NLS_CODEPAGE_950=n
CONFIG_NLS_CODEPAGE_932=n
CONFIG_NLS_CODEPAGE_949=n
CONFIG_NLS_CODEPAGE_874=n
CONFIG_NLS_ISO8859_8=n
CONFIG_NLS_CODEPAGE_1250=n
CONFIG_NLS_CODEPAGE_1251=n
CONFIG_NLS_ASCII=n
CONFIG_NLS_ISO8859_2=n
CONFIG_NLS_ISO8859_3=n
CONFIG_NLS_ISO8859_4=n
CONFIG_NLS_ISO8859_5=n
CONFIG_NLS_ISO8859_6=n
CONFIG_NLS_ISO8859_7=n
CONFIG_NLS_ISO8859_9=n
CONFIG_NLS_ISO8859_13=n
CONFIG_NLS_ISO8859_14=n
CONFIG_NLS_ISO8859_15=n
CONFIG_NLS_KOI8_R=n
CONFIG_NLS_KOI8_U=n
CONFIG_NLS_MAC_ROMAN=n
CONFIG_NLS_MAC_CELTIC=n
CONFIG_NLS_MAC_CENTEURO=n
CONFIG_NLS_MAC_CROATIAN=n
CONFIG_NLS_MAC_CYRILLIC=n
CONFIG_NLS_MAC_GAELIC=n
CONFIG_NLS_MAC_GREEK=n
CONFIG_NLS_MAC_ICELAND=n
CONFIG_NLS_MAC_INUIT=n
CONFIG_NLS_MAC_ROMANIAN=n
CONFIG_NLS_MAC_TURKISH=n
CONFIG_DLM=n
CONFIG_UNICODE=n
CONFIG_KEYS_REQUEST_CACHE=n
CONFIG_PERSISTENT_KEYRINGS=n
CONFIG_TRUSTED_KEYS=n
CONFIG_ENCRYPTED_KEYS=n
CONFIG_KEY_DH_OPERATIONS=n
CONFIG_PROC_MEM_ALWAYS_FORCE=y
CONFIG_PROC_MEM_FORCE_PTRACE=n
CONFIG_PROC_MEM_NO_FORCE=n
CONFIG_SECURITY=n
CONFIG_SECURITYFS=n
CONFIG_HARDENED_USERCOPY=n
CONFIG_FORTIFY_SOURCE=n
CONFIG_STATIC_USERMODEHELPER=n
CONFIG_DEFAULT_SECURITY_DAC=y
CONFIG_INIT_STACK_NONE=y
CONFIG_INIT_ON_ALLOC_DEFAULT_ON=n
CONFIG_INIT_ON_FREE_DEFAULT_ON=n
CONFIG_ZERO_CALL_USED_REGS=n
CONFIG_LIST_HARDENED=n
CONFIG_BUG_ON_DATA_CORRUPTION=n
CONFIG_CRYPTO_PCRYPT=n
CONFIG_CRYPTO_AUTHENC=n
CONFIG_CRYPTO_DH=n
CONFIG_CRYPTO_ECDSA=n
CONFIG_CRYPTO_ECRDSA=n
CONFIG_CRYPTO_CURVE25519=n
CONFIG_CRYPTO_AES_TI=n
CONFIG_CRYPTO_ARIA=n
CONFIG_CRYPTO_BLOWFISH=n
CONFIG_CRYPTO_CAMELLIA=n
CONFIG_CRYPTO_CAST5=n
CONFIG_CRYPTO_CAST6=n
CONFIG_CRYPTO_DES=n
CONFIG_CRYPTO_FCRYPT=n
CONFIG_CRYPTO_SERPENT=n
CONFIG_CRYPTO_SM4_GENERIC=n
CONFIG_CRYPTO_TWOFISH=n
CONFIG_CRYPTO_ADIANTUM=n
CONFIG_CRYPTO_CHACHA20=n
CONFIG_CRYPTO_CBC=n
CONFIG_CRYPTO_CTS=n
CONFIG_CRYPTO_HCTR2=n
CONFIG_CRYPTO_KEYWRAP=n
CONFIG_CRYPTO_LRW=n
CONFIG_CRYPTO_PCBC=n
CONFIG_CRYPTO_XTS=n
CONFIG_CRYPTO_AEGIS128=n
CONFIG_CRYPTO_CHACHA20POLY1305=n
CONFIG_CRYPTO_SEQIV=n
CONFIG_CRYPTO_ECHAINIV=n
CONFIG_CRYPTO_ESSIV=n
CONFIG_CRYPTO_BLAKE2B=n
CONFIG_CRYPTO_MD4=n
CONFIG_CRYPTO_MD5=m
CONFIG_CRYPTO_MICHAEL_MIC=n
CONFIG_CRYPTO_POLY1305=n
CONFIG_CRYPTO_RMD160=n
CONFIG_CRYPTO_SM3_GENERIC=n
CONFIG_CRYPTO_STREEBOG=n
CONFIG_CRYPTO_VMAC=n
CONFIG_CRYPTO_WP512=n
CONFIG_CRYPTO_XCBC=n
CONFIG_CRYPTO_XXHASH=n
CONFIG_CRYPTO_DEFLATE=n
CONFIG_CRYPTO_LZO=n
CONFIG_CRYPTO_842=n
CONFIG_CRYPTO_LZ4=n
CONFIG_CRYPTO_LZ4HC=n
CONFIG_CRYPTO_ZSTD=n
CONFIG_CRYPTO_ANSI_CPRNG=n
CONFIG_CRYPTO_DRBG_HASH=n
CONFIG_CRYPTO_DRBG_CTR=n
CONFIG_CRYPTO_USER_API_HASH=n
CONFIG_CRYPTO_USER_API_SKCIPHER=n
CONFIG_CRYPTO_USER_API_RNG=n
CONFIG_CRYPTO_USER_API_AEAD=n
CONFIG_CRYPTO_NHPOLY1305_NEON=n
CONFIG_CRYPTO_SHA1_ARM64_CE=n
CONFIG_CRYPTO_SHA256_ARM64=n
CONFIG_CRYPTO_SHA2_ARM64_CE=n
CONFIG_CRYPTO_SHA512_ARM64=n
CONFIG_CRYPTO_SHA512_ARM64_CE=n
CONFIG_CRYPTO_SHA3_ARM64=n
CONFIG_CRYPTO_SM3_ARM64_CE=n
CONFIG_CRYPTO_AES_ARM64_NEON_BLK=n
CONFIG_CRYPTO_AES_ARM64_BS=n
CONFIG_CRYPTO_SM4_ARM64_CE=n
CONFIG_CRYPTO_SM4_ARM64_CE_CCM=n
CONFIG_CRYPTO_SM4_ARM64_CE_GCM=n
CONFIG_CRYPTO_DEV_ATMEL_ECC=n
CONFIG_CRYPTO_DEV_ATMEL_SHA204A=n
CONFIG_CRYPTO_DEV_CCP=n
CONFIG_CRYPTO_DEV_SAFEXCEL=n
CONFIG_CRYPTO_DEV_CCREE=n
CONFIG_CRYPTO_DEV_HISI_SEC=n
CONFIG_CRYPTO_DEV_AMLOGIC_GXL=n
CONFIG_PKCS8_PRIVATE_KEY_PARSER=n
CONFIG_PKCS7_TEST_KEY=n
CONFIG_SIGNED_PE_FILE_VERIFICATION=n
CONFIG_FIPS_SIGNATURE_SELFTEST=n
CONFIG_SYSTEM_TRUSTED_KEYS=""
CONFIG_SYSTEM_EXTRA_CERTIFICATE=n
CONFIG_SECONDARY_TRUSTED_KEYRING=n
CONFIG_SYSTEM_BLACKLIST_KEYRING=n
CONFIG_PACKING=n
CONFIG_CORDIC=n
CONFIG_PRIME_NUMBERS=n
CONFIG_CRYPTO_LIB_CHACHA=n
CONFIG_CRYPTO_LIB_CURVE25519=n
CONFIG_CRYPTO_LIB_POLY1305=n
CONFIG_CRYPTO_LIB_CHACHA20POLY1305=n
CONFIG_CRC_ITU_T=n
CONFIG_CRC32_SELFTEST=n
CONFIG_CRC32_SLICEBY8=y
CONFIG_CRC32_SLICEBY4=n
CONFIG_CRC32_SARWATE=n
CONFIG_CRC32_BIT=n
CONFIG_CRC4=n
CONFIG_CRC7=n
CONFIG_CRC8=n
CONFIG_RANDOM32_SELFTEST=n
CONFIG_XZ_DEC=n
CONFIG_TEXTSEARCH_KMP=n
CONFIG_TEXTSEARCH_BM=n
CONFIG_TEXTSEARCH_FSM=n
CONFIG_SWIOTLB_DYNAMIC=n
CONFIG_DMA_RESTRICTED_POOL=n
CONFIG_DMA_API_DEBUG=n
CONFIG_GLOB_SELFTEST=n
CONFIG_IRQ_POLL=n
CONFIG_FONTS=n
CONFIG_STACKDEPOT_MAX_FRAMES=64
CONFIG_LWQ_TEST=n
CONFIG_PRINTK_CALLER=n
CONFIG_STACKTRACE_BUILD_ID=n
CONFIG_CONSOLE_LOGLEVEL_DEFAULT=7
CONFIG_CONSOLE_LOGLEVEL_QUIET=4
CONFIG_MESSAGE_LOGLEVEL_DEFAULT=4
CONFIG_DYNAMIC_DEBUG_CORE=n
CONFIG_SYMBOLIC_ERRNAME=y
CONFIG_FRAME_WARN=2048
CONFIG_HEADERS_INSTALL=n
CONFIG_DEBUG_SECTION_MISMATCH=n
CONFIG_SECTION_MISMATCH_WARN_ONLY=y
CONFIG_MAGIC_SYSRQ_DEFAULT_ENABLE=0x1
CONFIG_MAGIC_SYSRQ_SERIAL_SEQUENCE=""
CONFIG_PAGE_EXTENSION=n
CONFIG_SLUB_DEBUG_ON=n
CONFIG_PAGE_TABLE_CHECK=n
CONFIG_PAGE_POISONING=n
CONFIG_DEBUG_RODATA_TEST=n
CONFIG_DEBUG_WX=n
CONFIG_PER_VMA_LOCK_STATS=n
CONFIG_DEBUG_VM_PGTABLE=n
CONFIG_MEM_ALLOC_PROFILING=n
CONFIG_TEST_LOCKUP=n
CONFIG_SCHEDSTATS=n
CONFIG_WW_MUTEX_SELFTEST=n
CONFIG_DEBUG_IRQFLAGS=n
CONFIG_RCU_CPU_STALL_TIMEOUT=21
CONFIG_RCU_EXP_CPU_STALL_TIMEOUT=0
CONFIG_RCU_CPU_STALL_CPUTIME=n
CONFIG_SAMPLES=n
CONFIG_PID_IN_CONTEXTIDR=n
CONFIG_ARM64_RELOC_TEST=n
CONFIG_CORESIGHT=n
CONFIG_MEMTEST=n

EOF
echo "✅ H29K 内核参数注入完成（已修复固件string类型配置+预固化通用驱动配置，彻底杜绝NEW交互式编译报错）"
