#!/bin/bash
# https://github.com/P3TERX/Actions-OpenWrt
# File name: diy-part1.sh
# Description: OpenWrt DIY script part 1 (Before Update feeds)

set -euo pipefail  # 严格报错模式：任一非条件命令失败立即终止

# === 1. 软件源配置 ===
# 添加 QModem 软件源
echo 'src-git qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default

# === 2. 提取无线网卡驱动（精准对齐 25.12 分支时代） ===
git clone --depth 1 -b openwrt-25.12 --filter=blob:none --sparse https://github.com/immortalwrt/immortalwrt.git package/immortalwrt_temp
cd package/immortalwrt_temp
git sparse-checkout set package/kernel/aic8800
cd ../..
cp -r package/immortalwrt_temp/package/kernel/aic8800 package/kernel/aic8800
rm -rf package/immortalwrt_temp

# === 3. 安装 argon 主题
git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

# === 4. 管理蓝牙设备的LuCI
git clone https://github.com/I-agree/luci-app-bluetooth.git package/luci-app-bluetooth

# === 5. 磁盘扩容
git clone https://github.com/sirpdboy/luci-app-partexp.git package/luci-app-partexp

# === 6. axs5106触摸驱动
# git clone https://github.com/I-agree/axs5106.git package/kernel/modules/axs5106

# ======================== 【统一下载与文件校验中心】 ========================
echo "📥 开始统一拉取 H29K 编译所需的核心外置资源..."

# 创建全局所需的所有目录架构 (新增 files/www 网页容器支撑)
mkdir -p target/linux/rockchip/files/arch/arm64/boot/dts/rockchip \
         package/boot/uboot-rockchip/configs/hinlink/h29k \
         package/boot/uboot-rockchip/dts \
         target/linux/rockchip/image \
         package/boot/rkbin \
         files/etc/config/screen \
         files/etc/docker/mediamtx \
         files/etc/init.d \
         files/etc/fonts/conf.d \
         files/usr/bin \
         files/www \
         package/boot/uboot-rockchip/patches \
         package/boot/uboot-rockchip/BUG66 \
         files/usr/share/docker-images

BASE_URL="https://raw.githubusercontent.com/I-agree/H29K/main"
LOGO_URL="https://raw.githubusercontent.com/I-agree/H29K/main/JPG"

# [工具函数] 统一的下载与基础大小校验
download_and_check() {
    local url="$1"
    local dest="$2"
    echo "正在下载: $dest ..."
    if ! curl -fsSL --retry 3 --retry-delay 2 --connect-timeout 10 "$url" -o "$dest"; then
        echo "❌ 错误: $url 网络请求或连接失败！"
        exit 1
    fi
    if [ ! -s "$dest" ]; then
        echo "❌ 错误: $dest 下载成功但文件为空！"
        exit 1
    fi
}

# --- 批量下载核心底座组件 ---
download_and_check "${BASE_URL}/target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3528-hinlink-h29k.dts" "target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3528-hinlink-h29k.dts"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink-h29k-rk3528_defconfig" "package/boot/uboot-rockchip/configs/hinlink-h29k-rk3528_defconfig"
download_and_check "${BASE_URL}/target/linux/rockchip/image/armv8.mk" "target/linux/rockchip/image/armv8.mk"
download_and_check "${BASE_URL}/target/linux/rockchip/Makefile" "target/linux/rockchip/Makefile"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/Makefile" "package/boot/uboot-rockchip/Makefile"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k-u-boot.dtsi" "package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k-u-boot.dtsi"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/900-fix-mb-missing-header.patch" "package/boot/uboot-rockchip/patches/900-fix-mb-missing-header.patch"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/901-fix-dwc3-dma-proto.patch" "package/boot/uboot-rockchip/patches/901-fix-dwc3-dma-proto.patch"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k.dts" "package/boot/uboot-rockchip/dts/rk3528-hinlink-h29k.dts"
# download_and_check "${BASE_URL}/package/boot/rkbin/Makefile" "package/boot/rkbin/Makefile"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink/h29k/h29k.env" "package/boot/uboot-rockchip/configs/hinlink/h29k/h29k.env"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink/h29k/Makefile" "package/boot/uboot-rockchip/configs/hinlink/h29k/Makefile"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink/h29k/Kconfig" "package/boot/uboot-rockchip/configs/hinlink/h29k/Kconfig"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink/h29k/board.c" "package/boot/uboot-rockchip/configs/hinlink/h29k/board.c"
# download_and_check "${BASE_URL}/package/boot/uboot-rockchip/configs/hinlink/Kconfig" "package/boot/uboot-rockchip/configs/hinlink/Kconfig"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/997-uboot-rockchip-add-hinlink-h29k-target.patch" "package/boot/uboot-rockchip/patches/997-uboot-rockchip-add-hinlink-h29k-target.patch"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/998-add-hinlink-h29k-board-files.patch" "package/boot/uboot-rockchip/patches/998-add-hinlink-h29k-board-files.patch"
download_and_check "${BASE_URL}/package/boot/uboot-rockchip/patches/999-add-hinlink-h29k-support.patch" "package/boot/uboot-rockchip/patches/999-add-hinlink-h29k-support.patch"

# --- 统一拉取应用层开机 LOGO 组 ---
for i in 1 2 3; do
    download_and_check "${LOGO_URL}/LOGO${i}.jpg" "files/etc/config/screen/LOGO${i}.jpg"
done

# ==============================================================================
echo "🚀 [diy-part1.sh] 软件源与独立包与配置文件下载圆满完成！"

# ======================== 【H29K 主线内核配置合并注入】 ========================
CONFIG_FILE="target/linux/rockchip/armv8/config-6.12"

echo "📝 正在精准注入 H29K 专属内核配置到: $CONFIG_FILE"

# ========== 第一阶段：sed 原位替换（处理已知确切值的条目）==========
# 这些条目在原始 config-6.12 中有确定值，sed 可直接精确匹配
sed -i 's/^CONFIG_ARM64_SVE=y$/# CONFIG_ARM64_SVE is not set/' "$CONFIG_FILE"
sed -i 's/^CONFIG_CMA_SIZE_MBYTES=.*$/CONFIG_CMA_SIZE_MBYTES=32/' "$CONFIG_FILE"

cat >> "$CONFIG_FILE" << 'EOF'

# =================================================================
# 🔄 TCP BBR + FQ
# =================================================================
CONFIG_NET_SCHED=y
CONFIG_NET_SCH_DEFAULT=y
CONFIG_NET_SCH_FQ=y
CONFIG_DEFAULT_FQ=y
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=y
# CONFIG_DEFAULT_CUBIC is not set
CONFIG_DEFAULT_BBR=y

# =================================================================
# 📡 蓝牙完整协议栈 (AIC8800 SDIO WiFi+BT二合一)
# =================================================================
CONFIG_BT=y
CONFIG_BT_BREDR=y
CONFIG_BT_LE=y
CONFIG_BT_RFCOMM=y
CONFIG_BT_RFCOMM_TTY=y
CONFIG_BT_BNEP=y
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y
CONFIG_BT_HIDP=y
CONFIG_MMC_PWRSEQ_SIMPLE=y
CONFIG_MMC_PWRSEQ_EMMC=y
CONFIG_BT_HCIBTSDIO=m
# CONFIG_BT_HCIBTUSB is not set
# CONFIG_BT_HCIUART is not set

# =================================================================
# gpio-keys按键驱动 (设备没有按钮，但是保留)
# =================================================================
CONFIG_INPUT=y
CONFIG_INPUT_EVDEV=y
CONFIG_INPUT_KEYBOARD=y
# GPIO按键官方标准宏（OpenWrt打包依赖这个）
CONFIG_KEYBOARD_GPIO=y

# =================================================================
# 小屏幕 (ST7789V开启的全套配置)
# =================================================================
# 顶层DRM总开关
CONFIG_DRM=y
# DRM面板框架
CONFIG_DRM_PANEL=y
# 设备树
CONFIG_OF=y
# SPI总线
CONFIG_SPI=y
# 背光驱动
CONFIG_BACKLIGHT_CLASS_DEVICE=y
# ST7789V屏幕驱动
CONFIG_DRM_PANEL_SITRONIX_ST7789V=m

# =================================================================
# TSADC温度 (Rockchip 平台温控核心配置)
# =================================================================
# 基础架构
CONFIG_ARCH_ROCKCHIP=y
CONFIG_HAS_IOMEM=y
CONFIG_RESET_CONTROLLER=y

# 温控框架
CONFIG_THERMAL=y
CONFIG_THERMAL_OF=y
CONFIG_THERMAL_HWMON=y
CONFIG_THERMAL_NETLINK=y

# RK TSADC驱动
CONFIG_ROCKCHIP_THERMAL=y

# 温控冷却
CONFIG_CPU_THERMAL=y
CONFIG_CPU_FREQ_THERMAL=y
CONFIG_THERMAL_DEFAULT_GOV_STEP_WISE=y
CONFIG_THERMAL_GOV_STEP_WISE=y

# =================================================================
# 硬件真随机数 TRNG
# =================================================================
# 基础依赖
CONFIG_HAS_IOMEM=y
CONFIG_OF=y

# 硬件随机数框架
CONFIG_HW_RANDOM=y
# RK硬件TRNG驱动（DTS rng节点依赖此项）
CONFIG_HW_RANDOM_ROCKCHIP=y

# 推荐配套熵池相关（保证硬件随机数注入系统随机池）
CONFIG_CRYPTO=y
CONFIG_CRYPTO_RNG=y
CONFIG_CRYPTO_DRBG=y

# =================================================================
# rfkill-modem射频
# =================================================================
# 基础依赖
CONFIG_GPIOLIB=y
CONFIG_OF=y

# RFKILL总开关
CONFIG_RFKILL=y
# GPIO射频开关驱动（rfkill-modem DTS节点核心）
CONFIG_RFKILL_GPIO=y

# 推荐配套（默认开启）
CONFIG_RFKILL_LEDS=y
CONFIG_RFKILL_INPUT=y

# =================================================================
# PWM sysfs 相关配置
# =================================================================
# 全局基础
CONFIG_SYSFS=y
CONFIG_OF=y
CONFIG_HAS_IOMEM=y

# PWM总开关（开启后自动启用PWM sysfs导出）
CONFIG_PWM=y
CONFIG_PWM_SYSFS=y
# CONFIG_PWM_GPIO is not set

# RK硬件PWM驱动，匹配DTS pwm节点
CONFIG_PWM_ROCKCHIP=y

# 可选：PWM调试日志
# CONFIG_PWM_DEBUG is not set

# =================================================================
# SDIO 整套相关配置
# =================================================================
# MMC总开关+SDIO协议
CONFIG_MMC=y
CONFIG_MMC_SDIO=y
CONFIG_MMC_SDIO_IRQ=y

# SDIO模组GPIO上电复位
CONFIG_PWRSEQ_SIMPLE=y

# RK DW MMC控制器
CONFIG_MMC_DW=y
CONFIG_MMC_DW_PLTFM=y
CONFIG_MMC_DW_ROCKCHIP=y

# 全局基础依赖
CONFIG_OF=y
CONFIG_HAS_IOMEM=y
CONFIG_HAS_DMA=y

# =================================================================
# RK 平台 GPIO LED
# =================================================================
# LED总开关
CONFIG_NEW_LEDS=y
# LED sysfs类核心
CONFIG_LEDS_CLASS=y
# GPIO指示灯驱动（DTS gpio-leds）
CONFIG_LEDS_GPIO=y
# LED触发器总开关
CONFIG_LEDS_TRIGGERS=y
# 常用触发器
CONFIG_LEDS_TRIG_HEARTBEAT=y
CONFIG_LEDS_TRIG_NETDEV=y
CONFIG_LEDS_TRIG_MMC=y

# 全局前置依赖
CONFIG_GPIOLIB=y
CONFIG_OF=y

# =================================================================
# RGA 2D 硬件加速
# =================================================================
# media顶层
CONFIG_MEDIA_SUPPORT=y
CONFIG_MEDIA_SUPPORT_FILTER=y
CONFIG_MEDIA_SUBDRV_AUTOSELECT=y
CONFIG_MEDIA_PLATFORM_SUPPORT=y
# 关闭其余多媒体类型
# CONFIG_MEDIA_CAMERA_SUPPORT is not set
# CONFIG_MEDIA_ANALOG_TV_SUPPORT is not set
# CONFIG_MEDIA_DIGITAL_TV_SUPPORT is not set
# CONFIG_MEDIA_RADIO_SUPPORT is not set
# CONFIG_MEDIA_SDR_SUPPORT is not set
# CONFIG_MEDIA_TEST_SUPPORT is not set

# V4L2核心
CONFIG_VIDEO_DEV=y
# CONFIG_MEDIA_CONTROLLER is not set
CONFIG_V4L_MEM2MEM_DRIVERS=y

# v4l2-core 缓冲依赖
CONFIG_VIDEOBUF2_CORE=y

# RGA驱动
CONFIG_VIDEO_ROCKCHIP_RGA=y

# DMA内存必备
CONFIG_DMA_CMA=y
CONFIG_DMA_SHARED_BUFFER=y

# ===================== mm/Kconfig 配套(H29K RK3528 无磁盘Swap) =====================
# 关闭磁盘交换与zswap
# CONFIG_SWAP is not set
# CONFIG_ZSWAP is not set
# CONFIG_ZSWAP_DEFAULT_ON is not set
# CONFIG_ZSWAP_SHRINKER_DEFAULT_ON is not set

# ZRAM内存压缩交换(网关必备)
CONFIG_ZPOOL=y
CONFIG_ZRAM=y
CONFIG_ZRAM_MULTI_COMP=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
CONFIG_ZSMALLOC=y
# CONFIG_ZSMALLOC_STAT is not set
CONFIG_ZSMALLOC_CHAIN_SIZE=8
# CONFIG_ZBUD is not set
# CONFIG_Z3FOLD_DEPRECATED is not set
# CONFIG_ZRAM_WRITEBACK is not set

# CMA连续内存(GPU/屏幕/RGA依赖)
CONFIG_CMA=y
CONFIG_CMA_SYSFS=y
# CONFIG_CMA_DEBUGFS is not set
CONFIG_CMA_AREAS=8

# 内存整理与迁移
CONFIG_COMPACTION=y
CONFIG_MIGRATION=y
CONFIG_CONTIG_ALLOC=y

# Multi-Gen LRU 内存回收
CONFIG_LRU_GEN=y
CONFIG_LRU_GEN_ENABLE=y
# CONFIG_LRU_GEN_STATS is not set

# 透明巨页(显示屏UI加速)
CONFIG_TRANSPARENT_HUGEPAGE=y
CONFIG_TRANSPARENT_HUGEPAGE_MADVISE=y
# CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS is not set
# CONFIG_READ_ONLY_THP_FOR_FS is not set
CONFIG_THP_SWAP=y

# Slub内存分配安全加固
CONFIG_SLUB=y
CONFIG_SLUB_MERGE_DEFAULT=y
CONFIG_SLUB_FREELIST_RANDOM=y
CONFIG_SLUB_FREELIST_HARDENED=y
CONFIG_SLUB_BUCKETS=y
CONFIG_RANDOM_KMALLOC_CACHES=y
# CONFIG_SLUB_STATS is not set
# CONFIG_SLUB_TINY is not set
CONFIG_SLUB_CPU_PARTIAL=y

# 内存模型(无热插拔，平坦内存)
CONFIG_SELECT_MEMORY_MODEL=y
CONFIG_FLATMEM_MANUAL=y
CONFIG_FLATMEM=y
# CONFIG_SPARSEMEM is not set
# CONFIG_MEMORY_HOTPLUG is not set
# CONFIG_MEMORY_HOTREMOVE is not set

# KSM 页面合并，节省多进程内存
CONFIG_KSM=y
CONFIG_XXHASH=y

# 崩溃转储(开发保留，量产可注释关闭)
CONFIG_COREDUMP=y

# 安全内存基础配置
CONFIG_SHUFFLE_PAGE_ALLOCATOR=y
# CONFIG_COMPAT_BRK is not set
CONFIG_DEFAULT_MMAP_MIN_ADDR=65536
# CONFIG_MMAP_ALLOW_UNINITIALIZED is not set
CONFIG_MEMFD_CREATE=y
CONFIG_SECRETMEM=y
CONFIG_USERFAULTFD=y
CONFIG_PTE_MARKER_UFFD_WP=y
CONFIG_PER_VMA_LOCK=y

# 关闭调试测试项
# CONFIG_GUP_TEST is not set
# CONFIG_DMAPOOL_TEST is not set

# ===================== net/Kconfig 完整配置(H29K RK3528网关 IPv4+IPv6+WiFi+BT+NAT) =====================
CONFIG_NET=y
CONFIG_NLATTR=y
CONFIG_GENERIC_NET_UTILS=y
CONFIG_BPF=y
CONFIG_WANT_COMPAT_NETLINK_MESSAGES=y
CONFIG_COMPAT_NETLINK_MESSAGES=y
CONFIG_SKB_EXTENSIONS=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_XGRESS=y
CONFIG_NET_REDIRECT=y
CONFIG_SKB_DECRYPTED=y
CONFIG_PAGE_POOL=y
CONFIG_NET_DEVMEM=y

# TCP/IP 基础双栈
CONFIG_INET=y
# IPv4
CONFIG_IP_MULTICAST=y
CONFIG_IP_ADVANCED_ROUTER=y
CONFIG_IP_FIB_TRIE=y
CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IP_ROUTE_MULTIPATH=y
CONFIG_IP_VERBOSE_ROUTE_ERRORS=y
CONFIG_IP_PNP=y
CONFIG_IP_PNP_DHCP=y
CONFIG_IP_PNP_BOOTP=y
CONFIG_IP_PNP_RARP=y
CONFIG_NET_IPIP=m
CONFIG_NET_IPGRE_DEMUX=m
CONFIG_NET_IPGRE=m
CONFIG_NET_IPGRE_BROADCAST=y
CONFIG_ARP_MDIRECT=y
CONFIG_ARP_ACCEPT=y
CONFIG_TCP_FASTOPEN=y
CONFIG_TCP_FASTOPEN_CONNECT=y
CONFIG_TCP_MD5SIG=y
CONFIG_IP_TCPDIAG=y
CONFIG_UDP_SEGMENT=y
CONFIG_GRO=y
CONFIG_GSO=y
CONFIG_TSO=y
CONFIG_XFRM=y
CONFIG_XFRM_OFFLOAD=y
CONFIG_XFRM_STATEMONITOR=y
CONFIG_XFRM_SUB_POLICIES=y
CONFIG_XFRM_MIGRATE=y
CONFIG_XFRM_IPCOMP=m
# IPv6
CONFIG_IPV6=y
CONFIG_IPV6_MULTICAST=y
CONFIG_IPV6_ROUTER_PREF=y
CONFIG_IPV6_ROUTE_INFO=y
CONFIG_IPV6_ADVANCED_ROUTER=y
CONFIG_IPV6_FIB_TRIE=y
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_IPV6_MULTIPATH=y
CONFIG_IPV6_VERBOSE_ROUTE_ERRORS=y
CONFIG_IPV6_PNP=y
CONFIG_IPV6_PNP_DHCP6=y
CONFIG_IPV6_TUNNEL=m
CONFIG_IPV6_GRE=m
CONFIG_IPV6_MIP6=m
CONFIG_IPV6_ESP=m
CONFIG_IPV6_AH=m
CONFIG_IPV6_COMP=m
CONFIG_NF_NAT64=m
CONFIG_NF_NAT66=m
CONFIG_IPV6_NDISC_NODETYPE=y
CONFIG_IPV6_SEG6_LWTUNNEL=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_IPV6_RPL=m
CONFIG_IPV6_IOAM6=m
CONFIG_IPV6_ACCEPT_RA=y
CONFIG_IPV6_FORWARD=y
# MPTCP多路径TCP
CONFIG_MPTCP=y
CONFIG_MPTCP_FULLMESH=y
CONFIG_MPTCP_SCHED_BALANCER=y

# Netfilter 防火墙/NAT
CONFIG_NETFILTER=y
CONFIG_NETFILTER_ADVANCED=y
CONFIG_BRIDGE_NETFILTER=m
CONFIG_IP_NF_FILTER=m
CONFIG_IP_NF_NAT=m
CONFIG_IP_NF_TARGET_MASQUERADE=m
CONFIG_IP_NF_TARGET_REDIRECT=m
CONFIG_IP_NF_MANGLE=m
CONFIG_IP_NF_RAW=m
CONFIG_IP6_NF_FILTER=m
CONFIG_IP6_NAT=m
CONFIG_IP6_NF_MANGLE=m
CONFIG_IP6_NF_RAW=m
CONFIG_BRIDGE_NF_EBTABLES=m
CONFIG_NF_TABLES=y
CONFIG_NF_TABLES_IPV4=y
CONFIG_NF_TABLES_IPV6=y
CONFIG_NF_TABLES_BRIDGE=y
CONFIG_NFT_MASQ=m
CONFIG_NFT_REDIR=m
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CONNTRACK_MARK=y
CONFIG_NF_CONNTRACK_ZONES=y
CONFIG_NF_CT_PROTO_SCTP=y
CONFIG_NF_CT_PROTO_DCCP=y
CONFIG_NF_CT_PROTO_UDPLITE=y
CONFIG_NF_CT_ACCT=y
CONFIG_NF_CONNTRACK_TIMEOUT=y
CONFIG_NF_TABLES_SYNPROXY=m

# 有线以太网桥/VLAN
CONFIG_BRIDGE=y
CONFIG_VLAN_8021Q=m
CONFIG_DSA=y
CONFIG_SWITCHDEV=y
CONFIG_PHYLIB=y
CONFIG_NETWORK_PHY_TIMESTAMPING=y
CONFIG_PTP_1588_CLOCK=m
CONFIG_PTP_1588_CLOCK_PHY=m
# CONFIG_PTP_1588_CLOCK_INES is not set
# CONFIG_DP83640_PHY is not set

# 多核网络调度优化
CONFIG_RPS=y
CONFIG_RFS_ACCEL=y
CONFIG_XPS=y
CONFIG_BQL=y
CONFIG_NET_RX_BUSY_POLL=y
CONFIG_MAX_SKB_FRAGS=17
CONFIG_PCPU_DEV_REFCNT=y
CONFIG_FIB_RULES=y

# 流量调度
CONFIG_NET_SCH_CFQ=m
CONFIG_NET_SCH_CODEL=m
CONFIG_NET_SCH_FQ_CODEL=m
CONFIG_NET_SCH_HTB=m
CONFIG_NET_SCH_TBF=m

# 无线WiFi(AIC8800 SDIO)
CONFIG_WIRELESS=y
CONFIG_WIRELESS_EXT=y
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
# CONFIG_WEXT_SPY is not set
CONFIG_WEXT_PRIV=y
CONFIG_MAC80211=y
CONFIG_MAC80211_HWSIM=m
CONFIG_MAC80211_MESH=y
CONFIG_MAC80211_RC_MINSTREL=y
CONFIG_MAC80211_RC_MINSTREL_HT=y
CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y
# CONFIG_MAC80211_DEBUGFS is not set

# 通用网络配套
CONFIG_UNIX=y
CONFIG_NET_TLS=m
CONFIG_SCT=m
CONFIG_DCCP=m
CONFIG_DNS_RESOLVER=y
CONFIG_LWTUNNEL=y
CONFIG_LWTUNNEL_BPF=y
# CONFIG_MPLS is not set
# CONFIG_MPLS_IPTUNNEL is not set
# CONFIG_MPLS_GSO is not set
# CONFIG_MPLS_PSP is not set
# CONFIG_MPLS_ENTROPY is not set
# CONFIG_MPLS_STACK is not set
# CONFIG_NET_MPLS is not set
CONFIG_CGROUP_NET_PRIO=y
CONFIG_CGROUP_NET_CLASSID=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_NET_FLOW_LIMIT=y
CONFIG_NETWORK_SECMARK=y
CONFIG_SOCK_VALIDATE_XMIT=y
CONFIG_NET_SOCK_MSG=y
CONFIG_ETHTOOL_NETLINK=y
CONFIG_NET_PKTGEN=m
# CONFIG_NET_DROP_MONITOR is not set

# 量产关闭调试/废弃协议
# CONFIG_NET_HANDSHAKE_KUNIT_TEST is not set
# CONFIG_NET_TEST is not set
# CONFIG_PAGE_POOL_STATS is not set
# CONFIG_DST_CACHE is not set
# CONFIG_GRO_CELLS is not set
# CONFIG_NET_DEVLINK is not set
# CONFIG_ATM is not set
# CONFIG_APPLETALK is not set
# CONFIG_X25 is not set
# CONFIG_LAPB is not set
# CONFIG_PHONET is not set
# CONFIG_6LOWPAN is not set
# CONFIG_IEEE802154 is not set
# CONFIG_BATMAN_ADV is not set
# CONFIG_OPENVSWITCH is not set
# CONFIG_VMW_VSOCK is not set

# ===================== fs/Kconfig 配套(H29K RK3528网关) =====================
# 底层缓存与基础IO
CONFIG_DCACHE_WORD_ACCESS=y
CONFIG_BUFFER_HEAD=y
CONFIG_FS_IOMAP=y
CONFIG_FS_STACK=y
# CONFIG_LEGACY_DIRECT_IO is not set
CONFIG_FILE_LOCKING=y
CONFIG_FS_POSIX_ACL=y
CONFIG_EXPORTFS=y
CONFIG_EXPORTFS_BLOCK_OPS=y
CONFIG_IO_WQ=y
# CONFIG_VALIDATE_FS_PARSER is not set

# 嵌入式主文件系统
## EROFS 只读固件根文件系统(首选)
CONFIG_EROFS=y
CONFIG_EROFS_FS_XATTR=y
CONFIG_EROFS_FS_POSIX_ACL=y
CONFIG_EROFS_COMPRESSION=y
CONFIG_EROFS_ZSTD=y
CONFIG_EROFS_LZ4=y
# CONFIG_EROFS_DEBUG is not set

## EXT4 读写数据分区
CONFIG_EXT4_FS=y
CONFIG_EXT4_FS_XATTR=y
CONFIG_EXT4_FS_POSIX_ACL=y
CONFIG_EXT4_FS_SECURITY=y
CONFIG_JBD2=y
CONFIG_FS_MBCACHE=y
# CONFIG_EXT2_FS is not set
# CONFIG_EXT3_FS is not set
# 企业重型文件系统全部关闭
# CONFIG_XFS_FS is not set
# CONFIG_BTRFS_FS is not set
# CONFIG_REISERFS is not set
# CONFIG_JFS_FS is not set
# CONFIG_NILFS2 is not set

## U盘/TF卡 FAT/EXFAT/NTFS
CONFIG_FAT_FS=m
CONFIG_MSDOS_PARTITION=y
CONFIG_VFAT_FS=m
CONFIG_FAT_DEFAULT_CODEPAGE=437
CONFIG_FAT_DEFAULT_IOCHARSET="utf8"
CONFIG_EXFAT_FS=m
CONFIG_EXFAT_DEFAULT_IOCHARSET="utf8"
CONFIG_NTFS3_FS=m
CONFIG_NTFS3_XATTR=y
# CONFIG_NTFS is not set

# 虚拟内存文件系统
CONFIG_TMPFS=y
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_TMPFS_XATTR=y
CONFIG_TMPFS_QUOTA=y
# CONFIG_TMPFS_INODE64 is not set
CONFIG_SHMEM=y
CONFIG_HUGETLBFS=y
CONFIG_HUGETLB_PAGE=y
CONFIG_HUGETLB_PAGE_OPTIMIZE_VMEMMAP=y
CONFIG_ARCH_HAS_GIGANTIC_PAGE=y

# 伪文件系统 /proc /sys /config /efivar
CONFIG_PROC_FS=y
CONFIG_PROC_SYSCTL=y
CONFIG_SYSFS=y
CONFIG_KERNFS=y
CONFIG_CONFIGFS=m
CONFIG_EFIVARFS=y

# SPI Flash / 固件打包 / 崩溃日志
CONFIG_SQUASHFS=m
CONFIG_SQUASHFS_XATTR=y
CONFIG_SQUASHFS_COMP_LZ4=y
CONFIG_UBIFS=m
CONFIG_JFFS2=m
# CONFIG_CRAMFS is not set
# CONFIG_ROMFS is not set
CONFIG_PSTORE=y
CONFIG_PSTORE_CONSOLE=y
CONFIG_PSTORE_PMSG=y

# 容器核心分层文件系统
CONFIG_OVERLAY_FS=y
CONFIG_OVERLAY_FS_XINO=y
CONFIG_OVERLAY_FS_INDEX=y
CONFIG_AUTOFS4_FS=m
CONFIG_FUSE=m
CONFIG_FUSE_BLKDEV=m
# CONFIG_OVERLAY_FS_NFS_EXPORT is not set

# 安全加密、完整性、事件监控
CONFIG_FS_ENCRYPTION=y
CONFIG_FS_VERITY=y
CONFIG_FS_VERITY_BUILTIN_SIGNATURES=y
CONFIG_FSNOTIFY=y
CONFIG_INOTIFY_USER=y
CONFIG_FANOTIFY=y
CONFIG_QUOTA=y
CONFIG_QUOTA_NETLINK_INTERFACE=y
CONFIG_QFMT_V2=y

# 网络文件系统(内网共享可选)
CONFIG_NETWORK_FILESYSTEM=y
CONFIG_NFS_FS=m
CONFIG_NFS_V4=y
CONFIG_NFS_V4_1=y
CONFIG_NFS_V4_2=y
CONFIG_LOCKD=m
CONFIG_GRACE_PERIOD=m
CONFIG_NFS_ACL_SUPPORT=m
CONFIG_SMB_FS=m
# CONFIG_9P_FS is not set
# CONFIG_CEPH_FS is not set
CONFIG_NFS_V3=y
CONFIG_NFS_V3_ACL=y
CONFIG_PNFS_FILE_LAYOUT=m
CONFIG_PNFS_BLOCK=m
CONFIG_PNFS_FLEXFILE_LAYOUT=m
CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN="kernel.org"
# CONFIG_NFS_V4_1_MIGRATION is not set
CONFIG_NFS_V4_SECURITY_LABEL=y
# CONFIG_ROOT_NFS is not set
# CONFIG_NFS_FSCACHE is not set
# CONFIG_NFS_USE_LEGACY_DNS is not set
CONFIG_NFS_USE_KERNEL_DNS=y
# CONFIG_NFS_DEBUG is not set
CONFIG_NFS_DISABLE_UDP_SUPPORT=y
CONFIG_NFS_V4_2_READ_PLUS=y

# 无NVDIMM持久内存，DAX全部关闭
# CONFIG_FS_DAX is not set
# CONFIG_FS_DAX_PMD is not set
# CONFIG_FS_DAX_LIMITED is not set

# 光驱无用关闭
# CONFIG_ISOFS is not set
# CONFIG_UDF_FS is not set

# 小众杂项文件系统全部禁用
# CONFIG_MISC_FILES is not set
# CONFIG_HFS_FS is not set
# CONFIG_HFSPLUS_FS is not set
# CONFIG_VBOXSF is not set
# CONFIG_MINIX_FS is not set

# ===================== security/Kconfig H29K RK3528网关安全配置 =====================
# 基础安全框架
CONFIG_SECURITY=y
CONFIG_SECURITYFS=y
CONFIG_SECURITY_NETWORK=y
CONFIG_SECURITY_NETWORK_XFRM=y
CONFIG_SECURITY_PATH=y
CONFIG_SECURITY_DMESG_RESTRICT=y
CONFIG_PROC_MEM_FORCE_PTRACE=y
# CONFIG_PROC_MEM_ALWAYS_FORCE is not set
# CONFIG_PROC_MEM_NO_FORCE is not set

# 内存/字符串溢出加固（ARM64 clang无llvm inreg Bug限制）
CONFIG_HARDENED_USERCOPY=y
CONFIG_FORTIFY_SOURCE=y
# LSM低地址保护，防空指针漏洞
CONFIG_LSM_MMAP_MIN_ADDR=65536

# 静态用户态助手，限制内核调用外部程序
CONFIG_STATIC_USERMODEHELPER=y
CONFIG_STATIC_USERMODEHELPER_PATH="/sbin/usermode-helper"

# LSM 安全模块配置（轻量防护，关闭重型SELinux/AppArmor）
CONFIG_LSM="landlock,lockdown,yama,loadpin,safesetid,ipe"
CONFIG_DEFAULT_SECURITY_DAC=y
# 轻型LSM开启
CONFIG_SECURITY_LOCKDOWN_LSM=y
CONFIG_LOCKDOWN_DEFAULT=integrity
CONFIG_SECURITY_YAMA=y
CONFIG_YAMA_PTRACE_SCOPE=1
CONFIG_YAMA_PROTECT_KERNEL_PTRACE=y
CONFIG_SECURITY_LANDLOCK=y
CONFIG_SECURITY_LOADPIN=y
CONFIG_LOADPIN_VERIFY=y
CONFIG_SECURITY_SAFESETID=y
CONFIG_SECURITY_IPE=y
# 重型MAC全部关闭
# CONFIG_SECURITY_SELINUX is not set
# CONFIG_SECURITY_SMACK is not set
# CONFIG_SECURITY_TOMOYO is not set
# CONFIG_SECURITY_APPARMOR is not set

# 密钥与文件完整性校验(WiFi/固件防篡改)
CONFIG_KEYS=y
CONFIG_KEYS_COMPAT=y
CONFIG_PERSISTENT_KEYRINGS=y
CONFIG_TRUSTED_KEYS=y
CONFIG_ENCRYPTED_KEYS=y
CONFIG_INTEGRITY=y
CONFIG_IMA=y
CONFIG_IMA_MEASURE_PCR_IDX=10
CONFIG_IMA_APPRAISE=y
CONFIG_EVM=y

# 无Intel TXT/IB硬件，关闭
# CONFIG_INTEL_TXT is not set
# CONFIG_SECURITY_INFINIBAND is not set

# 内核全量编译加固 (security/Kconfig.hardening)
CONFIG_STACK_PROTECTOR=y
CONFIG_STACK_PROTECTOR_STRONG=y
CONFIG_STACK_CANARIES=y
CONFIG_RANDOMIZE_BASE=y
CONFIG_RANDOMIZE_MEMORY=y
CONFIG_SHADOW_STACK=y
CONFIG_CFI_CLANG=y
# CONFIG_CFI_PERMISSIVE is not set
CONFIG_KPTI=y
CONFIG_UNMAP_KERNEL_AT_EL0=y
CONFIG_HARDEN_BRANCH_PREDICTOR=y
CONFIG_SPEC_STORE_BYPASS_SECURE=y
CONFIG_OBJECT_POISON=y
CONFIG_INIT_ON_ALLOC=y
CONFIG_INIT_ON_FREE_DEFAULT=y
CONFIG_ZERO_CALL_USED_REGS=y
CONFIG_DEBUG_WX=y
# CONFIG_RANDOMIZE_MODULE_REGION_FULL is not set

# ===================== crypto/Kconfig H29K RK3528 加密配置(含Twofish) =====================
CONFIG_CRYPTO=y
CONFIG_CRYPTO_LIB_UTILS=y
# 基础算法API
CONFIG_CRYPTO_ALGAPI=y
CONFIG_CRYPTO_ALGAPI2=y
CONFIG_CRYPTO_AEAD=y
CONFIG_CRYPTO_AEAD2=y
CONFIG_CRYPTO_SIG=y
CONFIG_CRYPTO_SIG2=y
CONFIG_CRYPTO_SKCIPHER=y
CONFIG_CRYPTO_SKCIPHER2=y
CONFIG_CRYPTO_HASH=y
CONFIG_CRYPTO_HASH2=y
CONFIG_CRYPTO_RNG=y
CONFIG_CRYPTO_RNG2=y
CONFIG_CRYPTO_RNG_DEFAULT=y
CONFIG_CRYPTO_AKCIPHER=y
CONFIG_CRYPTO_AKCIPHER2=y
CONFIG_CRYPTO_KPP=y
CONFIG_CRYPTO_KPP2=y
CONFIG_CRYPTO_ACOMP=y
CONFIG_CRYPTO_ACOMP2=y
CONFIG_CRYPTO_MANAGER=y
CONFIG_CRYPTO_MANAGER2=y
CONFIG_CRYPTO_NULL=y
CONFIG_CRYPTO_NULL2=y
CONFIG_CRYPTO_CRYPTD=y
CONFIG_CRYPTO_PCRYPT=y
CONFIG_CRYPTO_AUTHENC=y
CONFIG_CRYPTO_SIMD=y
CONFIG_CRYPTO_ENGINE=y
# 关闭加密自测加速启动
CONFIG_CRYPTO_MANAGER_DISABLE_TESTS=y
# CONFIG_CRYPTO_MANAGER_EXTRA_TESTS is not set
# 用户态加密接口
CONFIG_CRYPTO_USER=y
CONFIG_CRYPTO_USER_API_HASH=y
CONFIG_CRYPTO_USER_API_SKCIPHER=y
CONFIG_CRYPTO_USER_API_RNG=y
CONFIG_CRYPTO_USER_API_AEAD=y
CONFIG_CRYPTO_USER_API_ENABLE_OBSOLETE=y
CONFIG_XOR_BLOCKS=y

# 公钥/密钥协商
CONFIG_CRYPTO_RSA=y
CONFIG_MPILIB=y
CONFIG_ASN1=y
CONFIG_CRYPTO_DH=y
CONFIG_CRYPTO_DH_RFC7919=y
CONFIG_CRYPTO_ECC=y
CONFIG_CRYPTO_ECDH=y
CONFIG_CRYPTO_ECDSA=y
CONFIG_CRYPTO_CURVE25519=y
CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
CONFIG_CRYPTO_LIB_CURVE25519_INTERNAL=y
# CONFIG_CRYPTO_DH_RFC7919_GROUPS is not set

# 分组密码（包含Twofish）
CONFIG_CRYPTO_AES=y
CONFIG_CRYPTO_LIB_AES=y
CONFIG_CRYPTO_AES_T=y
# Twofish AES决赛无专利算法
CONFIG_CRYPTO_TWOFISH=y
CONFIG_CRYPTO_TWOFISH_COMMON=y
CONFIG_CRYPTO_BLOWFISH=y
CONFIG_CRYPTO_BLOWFISH_COMMON=y
CONFIG_CRYPTO_SERPENT=y
# 国密SM4
CONFIG_CRYPTO_SM4_GENERIC=y
CONFIG_CRYPTO_SM4=y
CONFIG_CRYPTO_CAMELLIA=y
CONFIG_CRYPTO_ARIA=y
CONFIG_CRYPTO_DES=y
CONFIG_CRYPTO_LIB_DES=y
CONFIG_CRYPTO_CAST5=y
CONFIG_CRYPTO_CAST6=y
CONFIG_CRYPTO_CAST_COMMON=y

# 流加密
CONFIG_CRYPTO_CHACHA20=y
CONFIG_CRYPTO_LIB_CHACHA_GENERIC=y
CONFIG_CRYPTO_LIB_CHACHA_INTERNAL=y
CONFIG_CRYPTO_CHACHA20POLY1305=y
CONFIG_CRYPTO_POLY1305=y
CONFIG_CRYPTO_LIB_POLY1305_GENERIC=y
CONFIG_CRYPTO_ADIANTUM=y
CONFIG_CRYPTO_ARC4=y

# 加密模式 IPSec/磁盘加密
CONFIG_CRYPTO_CBC=y
CONFIG_CRYPTO_CTR=y
CONFIG_CRYPTO_CTS=y
CONFIG_CRYPTO_ECB=y
CONFIG_CRYPTO_GCM=y
CONFIG_CRYPTO_CCM=y
CONFIG_CRYPTO_XTS=y
CONFIG_CRYPTO_LRW=y
CONFIG_CRYPTO_HCTR2=y
CONFIG_CRYPTO_XCTR=y
CONFIG_CRYPTO_KEYWRAP=y
CONFIG_CRYPTO_SEQIV=y
CONFIG_CRYPTO_ECHAINIV=y
CONFIG_CRYPTO_ESSIV=y
CONFIG_CRYPTO_AEGIS128=y
CONFIG_CRYPTO_AEGIS128_SIMD=y

# 哈希 & MAC
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_LIB_SHA1=y
CONFIG_CRYPTO_SHA256=y
CONFIG_CRYPTO_LIB_SHA256=y
CONFIG_CRYPTO_SHA512=y
CONFIG_CRYPTO_SHA3=y
CONFIG_CRYPTO_BLAKE2B=y
# 国密SM3
CONFIG_CRYPTO_SM3_GENERIC=y
CONFIG_CRYPTO_SM3=y
CONFIG_CRYPTO_HMAC=y
CONFIG_CRYPTO_CMAC=y
CONFIG_CRYPTO_XCBC=y
CONFIG_CRYPTO_MICHAEL_MIC=y
# CRC校验
CONFIG_CRYPTO_CRC32=y
CONFIG_CRYPTO_CRC32C=y
CONFIG_CRYPTO_CRCT10DIF=y
CONFIG_CRYPTO_CRC64_ROCKSOFT=y
# 高速非加密哈希
CONFIG_CRYPTO_XXHASH=y
CONFIG_XXHASH=y
# 兼容老旧哈希
CONFIG_CRYPTO_MD4=y
CONFIG_CRYPTO_MD5=y

# zswap/zram/EROFS 压缩算法
CONFIG_CRYPTO_LZO=y
CONFIG_LZO_COMPRESS=y
CONFIG_LZO_DECOMPRESS=y
CONFIG_CRYPTO_LZ4=y
CONFIG_LZ4_COMPRESS=y
CONFIG_LZ4_DECOMPRESS=y
CONFIG_CRYPTO_LZ4HC=y
CONFIG_CRYPTO_ZSTD=y
CONFIG_ZSTD_COMPRESS=y
CONFIG_ZSTD_DECOMPRESS=y
CONFIG_CRYPTO_DEFLATE=y
CONFIG_ZLIB_INFLATE=y
CONFIG_ZLIB_DEFLATE=y
CONFIG_CRYPTO_842=y
CONFIG_842_COMPRESS=y
CONFIG_842_DECOMPRESS=y

# 随机数生成（配套RK TRNG硬件随机）
CONFIG_CRYPTO_DRBG_MENU=y
CONFIG_CRYPTO_DRBG=y
CONFIG_CRYPTO_DRBG_HMAC=y
CONFIG_CRYPTO_DRBG_HASH=y
CONFIG_CRYPTO_DRBG_CTR=y
CONFIG_CRYPTO_JITTERENTROPY=y
# CONFIG_CRYPTO_ANSI_CPRNG is not set

# 证书/非对称密钥（IMA固件校验）
source "crypto/asymmetric_keys/Kconfig"
source "certs/Kconfig"
CONFIG_SYSTEM_DATA_VERIFICATION=y
CONFIG_TRUSTED_KEYRING=y

# 关闭测试模块
# CONFIG_CRYPTO_TEST is not set
# 普通网关关闭FIPS合规
# CONFIG_CRYPTO_FIPS is not set
# 废弃小众算法按需关闭
# CONFIG_CRYPTO_WP512 is not set
# CONFIG_CRYPTO_RMD160 is not set
# CONFIG_CRYPTO_STREEBOG is not set


# ===================== certs/Kconfig H29K RK3528 配置 =====================
# 模块签名密钥文件路径（默认自动生成签名密钥）
CONFIG_MODULE_SIG_KEY="certs/signing_key.pem"
# 使用RSA算法做内核模块签名
CONFIG_MODULE_SIG_KEY_TYPE_RSA=y
# CONFIG_MODULE_SIG_KEY_TYPE_ECDSA is not set

# 系统全局可信密钥环（IMA、模块验签依赖，必须开启）
CONFIG_SYSTEM_TRUSTED_KEYRING=y
# 内置可信根证书文件，留空使用内核内置信任链
CONFIG_SYSTEM_TRUSTED_KEYS=""

# 禁止内核镜像预留证书追加空间（量产固化固件，无需后期插入证书）
# CONFIG_SYSTEM_EXTRA_CERTIFICATE is not set

# 二级可信密钥环，支持运行时加载可信证书
CONFIG_SECONDARY_TRUSTED_KEYRING=y
# 仅允许内置根证书签名的外部证书加入二级密钥环，收紧安全策略
CONFIG_SECONDARY_TRUSTED_KEYRING_SIGNED_BY_BUILTIN=y

# 全局密钥黑名单（拉黑失效、恶意证书）
CONFIG_SYSTEM_BLACKLIST_KEYRING=y
CONFIG_SYSTEM_BLACKLIST_HASH_LIST=""

# 证书吊销列表支持
CONFIG_SYSTEM_REVOCATION_LIST=y
CONFIG_SYSTEM_REVOCATION_KEYS=""

# 允许root加载签名后的黑名单密钥
CONFIG_SYSTEM_BLACKLIST_AUTH_UPDATE=y

# ===================== drivers/crypto H29K RK3528 硬件加密配置 =====================
# 硬件加密总开关
CONFIG_CRYPTO_HW=y

# Rockchip 内置硬件加密引擎(必开，RK3528原生硬件AES/SHA/DES加速)
CONFIG_CRYPTO_DEV_ROCKCHIP=y
# 量产关闭加密调试统计
# CONFIG_CRYPTO_DEV_ROCKCHIP_DEBUG is not set

# 以下全部非RK平台硬件加密，统一关闭
# CONFIG_CRYPTO_DEV_PADLOCK is not set
# CONFIG_CRYPTO_DEV_PADLOCK_AES is not set
# CONFIG_CRYPTO_DEV_PADLOCK_SHA is not set
# CONFIG_CRYPTO_DEV_GEODE is not set
# CONFIG_ZCRYPT is not set
# CONFIG_PKEY is not set
# CONFIG_PKEY_CCA is not set
# CONFIG_PKEY_EP11 is not set
# CONFIG_PKEY_PCKMO is not set
# CONFIG_CRYPTO_PAES_S390 is not set
# CONFIG_S390_PRNG is not set
# CONFIG_CRYPTO_DEV_NIAGARA2 is not set
# CONFIG_CRYPTO_DEV_SL3516 is not set
# CONFIG_CRYPTO_DEV_SL3516_DEBUG is not set
# CONFIG_CRYPTO_DEV_HIFN_795X is not set
# CONFIG_CRYPTO_DEV_HIFN_795X_RNG is not set
# CONFIG_CRYPTO_DEV_TALITOS is not set
# CONFIG_CRYPTO_DEV_TALITOS1 is not set
# CONFIG_CRYPTO_DEV_TALITOS2 is not set
# CONFIG_CRYPTO_DEV_PPC4XX is not set
# CONFIG_HW_RANDOM_PPC4XX is not set
# CONFIG_CRYPTO_DEV_OMAP is not set
# CONFIG_CRYPTO_DEV_OMAP_SHAM is not set
# CONFIG_CRYPTO_DEV_OMAP_AES is not set
# CONFIG_CRYPTO_DEV_OMAP_DES is not set
# CONFIG_CRYPTO_DEV_SAHARA is not set
# CONFIG_CRYPTO_DEV_EXYNOS_RNG is not set
# CONFIG_CRYPTO_DEV_S5P is not set
# CONFIG_CRYPTO_DEV_EXYNOS_HASH is not set
# CONFIG_CRYPTO_DEV_NX is not set
# CONFIG_CRYPTO_DEV_ATMEL_AUTHENC is not set
# CONFIG_CRYPTO_DEV_ATMEL_AES is not set
# CONFIG_CRYPTO_DEV_ATMEL_TDES is not set
# CONFIG_CRYPTO_DEV_ATMEL_SHA is not set
# CONFIG_CRYPTO_DEV_ATMEL_ECC is not set
# CONFIG_CRYPTO_DEV_ATMEL_SHA204A is not set
# CONFIG_CRYPTO_DEV_CCP is not set
# CONFIG_CRYPTO_DEV_MXS_DCP is not set
# CONFIG_CRYPTO_DEV_CAVIUM_ZIP is not set
# CONFIG_CRYPTO_DEV_QCE is not set
# CONFIG_CRYPTO_DEV_QCE_SKCIPHER is not set
# CONFIG_CRYPTO_DEV_QCE_SHA is not set
# CONFIG_CRYPTO_DEV_QCE_AEAD is not set
# CONFIG_CRYPTO_DEV_QCOM_RNG is not set
# CONFIG_CRYPTO_DEV_IMGTEC_HASH is not set
# CONFIG_CRYPTO_DEV_TEGRA is not set
# CONFIG_CRYPTO_DEV_ZYNQMP_AES is not set
# CONFIG_CRYPTO_DEV_ZYNQMP_SHA3 is not set
# CONFIG_CRYPTO_DEV_CHELSIO is not set
# CONFIG_CRYPTO_DEV_VIRTIO is not set
# CONFIG_CRYPTO_DEV_BCM_SPU is not set
# CONFIG_CRYPTO_DEV_STM32_AES is not set
# CONFIG_CRYPTO_DEV_STM32_VREFBUF is not set
# CONFIG_CRYPTO_DEV_STM32_PWR is not set
# CONFIG_CRYPTO_DEV_SAFEXCEL is not set
# CONFIG_CRYPTO_DEV_ARTPEC6 is not set
# CONFIG_CRYPTO_DEV_CCREE is not set
# CONFIG_CRYPTO_DEV_HISILICON is not set
# CONFIG_CRYPTO_DEV_AMLOGIC is not set
# CONFIG_CRYPTO_DEV_SA2UL is not set
# CONFIG_CRYPTO_DEV_STARFIVE is not set

CONFIG_ASYMMETRIC_KEY_TYPE=y
CONFIG_ASYMMETRIC_PUBLIC_KEY_SUBTYPE=y
CONFIG_X509_CERTIFICATE_PARSER=y
# CONFIG_PKCS8_PRIVATE_KEY_PARSER is not set
CONFIG_PKCS7_MESSAGE_PARSER=y
# CONFIG_PKCS7_TEST_KEY is not set
# CONFIG_SIGNED_PE_FILE_VERIFICATION is not set
# CONFIG_FIPS_SIGNATURE_SELFTEST is not set

# ================= arch/arm64/crypto RK3528 CPU加密指令加速 =================
# 前置依赖必须开启
CONFIG_ARM64=y
CONFIG_KERNEL_MODE_NEON=y
CONFIG_CRYPTO=y
CONFIG_CRC_T10DIF=y

# Hash 哈希系列
CONFIG_CRYPTO_GHASH_ARM64_CE=y
CONFIG_CRYPTO_NHPOLY1305_NEON=y
CONFIG_CRYPTO_POLY1305_NEON=y
CONFIG_CRYPTO_SHA1_ARM64_CE=y
CONFIG_CRYPTO_SHA256_ARM64=y
CONFIG_CRYPTO_SHA2_ARM64_CE=y
CONFIG_CRYPTO_SHA512_ARM64=y
CONFIG_CRYPTO_SHA512_ARM64_CE=y
CONFIG_CRYPTO_SHA3_ARM64=y

# 国密SM3
CONFIG_CRYPTO_SM3_NEON=y
CONFIG_CRYPTO_SM3_ARM64_CE=y

# POLYVAL(HCTR2依赖)
CONFIG_CRYPTO_POLYVAL_ARM64_CE=y

# AES 对称加密全套
CONFIG_CRYPTO_AES_ARM64=y
CONFIG_CRYPTO_AES_ARM64_CE=y
CONFIG_CRYPTO_AES_ARM64_CE_BLK=y
CONFIG_CRYPTO_AES_ARM64_NEON_BLK=y
CONFIG_CRYPTO_AES_ARM64_BS=y
# AES CCM AEAD(Wifi/IPSec必备)
CONFIG_CRYPTO_AES_ARM64_CE_CCM=y

# ChaCha20-Poly1305 WireGuard加速
CONFIG_CRYPTO_CHACHA20_NEON=y

# 国密SM4全套
CONFIG_CRYPTO_SM4_ARM64_CE=y
CONFIG_CRYPTO_SM4_ARM64_CE_BLK=y
CONFIG_CRYPTO_SM4_ARM64_NEON_BLK=y
CONFIG_CRYPTO_SM4_ARM64_CE_CCM=y
CONFIG_CRYPTO_SM4_ARM64_CE_GCM=y

# SCSI CRC硬件加速
CONFIG_CRYPTO_CRCT10DIF_ARM64_CE=y

# ===================== lib/Kconfig RK3528 H29K 网关通用库配置 =====================
# 基础内存/IO工具
CONFIG_BITREVERSE=y
CONFIG_PACKING=y
CONFIG_LINEAR_RANGES=y
CONFIG_BINARY_PRINTF=y
CONFIG_GENERIC_IOMAP=y
CONFIG_GENERIC_PCI_IOMAP=y
# CONFIG_NO_GENERIC_PCI_IOPORT_MAP is not set
CONFIG_HAS_IOMEM=y
CONFIG_HAS_IOPORT=y
CONFIG_HAS_IOPORT_MAP=y
# CONFIG_INDIRECT_PIO is not set
# CONFIG_INDIRECT_IOMEM is not set
# CONFIG_INDIRECT_IOMEM_FALLBACK is not set
CONFIG_GENERIC_STRNCPY_FROM_USER=y
CONFIG_GENERIC_STRNLEN_USER=y
# CONFIG_ARCH_HAS_STRNCPY_FROM_USER is not set
# CONFIG_ARCH_HAS_STRNLEN_USER is not set
CONFIG_GENERIC_NET_UTILS=y
CONFIG_ARCH_USE_CMPXCHG_LOCKREF=y
CONFIG_ARCH_HAS_FAST_MULTIPLIER=y
CONFIG_ARCH_USE_SYM_ANNOTATIONS=y
# CONFIG_TRACE_MMIO is not set
CONFIG_DQL=y
CONFIG_SGL_ALLOC=y
CONFIG_NLATTR=y
CONFIG_GLOB=y
# CONFIG_GLOB_SELFTEST is not set
CONFIG_CHECK_SIGNATURE=y
CONFIG_CPUMASK_OFFSTACK=y
# CONFIG_FORCE_NR_CPUS is not set
CONFIG_CPU_RMAP=y
CONFIG_SG_SPLIT=y
CONFIG_SG_POOL=y
# CONFIG_ARCH_NO_SG_CHAIN is not set
CONFIG_INTERVAL_TREE=y
CONFIG_INTERVAL_TREE_SPAN_ITER=y
CONFIG_XARRAY_MULTI=y
CONFIG_ASSOCIATIVE_ARRAY=y
CONFIG_BTREE=y
CONFIG_CLOSURES=y
CONFIG_STACKDEPOT=y
# CONFIG_STACKDEPOT_ALWAYS_INIT is not set
CONFIG_STACKDEPOT_MAX_FRAMES=64
# CONFIG_REF_TRACKER is not set
CONFIG_SBITMAP=y
CONFIG_GENERIC_ATOMIC64=y
CONFIG_LRU_CACHE=y
CONFIG_CLZ_TAB=y
CONFIG_IRQ_POLL=y
CONFIG_DIMLIB=y
CONFIG_LIBFDT=y
CONFIG_OID_REGISTRY=y
CONFIG_UCS2=y
CONFIG_ASN1_ENCODER=m
CONFIG_POLYNOMIAL=m
CONFIG_FIRMWARE_TABLE=y
# CONFIG_PLDMFW is not set

# CRC 校验全套（eMMC/TF/WiFi/文件系统）
CONFIG_CRC32=y
CONFIG_CRC32_SLICEBY8=y
# CONFIG_CRC32_SLICEBY4 is not set
# CONFIG_CRC32_SARWATE is not set
# CONFIG_CRC32_BIT is not set
# CONFIG_CRC32_SELFTEST is not set
CONFIG_CRC_CCITT=m
CONFIG_CRC16=m
CONFIG_CRC_ITU_T=m
CONFIG_CRC64=y
CONFIG_CRC64_ROCKSOFT=y
CONFIG_CRC_T10DIF=m
CONFIG_CRC4=m
CONFIG_CRC7=m
CONFIG_CRC8=m
CONFIG_LIBCRC32C=y
CONFIG_XXHASH=y

# 压缩库 zswap/EROFS/Squashfs
CONFIG_LZO_COMPRESS=y
CONFIG_LZO_DECOMPRESS=y
CONFIG_LZ4_COMPRESS=y
CONFIG_LZ4_DECOMPRESS=y
CONFIG_LZ4HC_COMPRESS=m
CONFIG_ZSTD_COMMON=y
CONFIG_ZSTD_COMPRESS=y
CONFIG_ZSTD_DECOMPRESS=y
CONFIG_ZLIB_INFLATE=y
CONFIG_ZLIB_DEFLATE=y
# CONFIG_ZLIB_DFLTCC is not set
CONFIG_842_COMPRESS=m
CONFIG_842_DECOMPRESS=m
CONFIG_DECOMPRESS_GZIP=y
CONFIG_DECOMPRESS_LZO=y
CONFIG_DECOMPRESS_LZ4=y
CONFIG_DECOMPRESS_ZSTD=y
CONFIG_DECOMPRESS_BZIP2=m
CONFIG_DECOMPRESS_LZMA=m
CONFIG_DECOMPRESS_XZ=m
source "lib/xz/Kconfig"

# 加密数学库 RSA/ECC/NAND ECC
CONFIG_MPILIB=y
CONFIG_BCH=y
# CONFIG_BCH_CONST_PARAMS is not set
CONFIG_REED_SOLOMON=m
CONFIG_REED_SOLOMON_DEC8=y
CONFIG_REED_SOLOMON_ENC8=y
# CONFIG_RAID6_PQ is not set
# CONFIG_RAID6_PQ_BENCHMARK is not set
CONFIG_SIGNATURE=y
# CONFIG_RANDOM32_SELFTEST is not set
CONFIG_TEXTSEARCH=y
CONFIG_TEXTSEARCH_KMP=m
CONFIG_TEXTSEARCH_BM=m
CONFIG_TEXTSEARCH_FSM=m

# DMA/RGA/SDIO 驱动依赖
CONFIG_IOMMU_HELPER=y
CONFIG_STMP_DEVICE=y
CONFIG_GENERIC_ALLOCATOR=y

# 审计安全配套
CONFIG_AUDIT_GENERIC=y
# CONFIG_AUDIT_ARCH_COMPAT_GENERIC is not set
# CONFIG_AUDIT_COMPAT_GENERIC is not set

# 量产调试关闭项
# CONFIG_TRACE_MMIO is not set
# CONFIG_REF_TRACKER is not set
# CONFIG_CRC32_SELFTEST is not set
# CONFIG_GLOB_SELFTEST is not set
# CONFIG_LWQ_TEST is not set
# CONFIG_PARMAN is not set
# CONFIG_OBJAGG is not set
# CONFIG_RAID6_PQ is not set
# CONFIG_PLDMFW is not set
# CONFIG_INDIRECT_PIO is not set
# CONFIG_INDIRECT_IOMEM is not set

# ===================== Documentation/Kconfig配置 =====================
# Documentation 文档校验仅编译测试可用，量产全部关闭
# CONFIG_WARN_MISSING_DOCUMENTS is not set
# CONFIG_WARN_ABI_ERRORS is not set
# 量产关闭全局编译测试开关
# CONFIG_COMPILE_TEST is not set

# ===================== drivers/regulator 调压全套配置(RK3528 H29K) =====================
# 电压/电流调节器总框架(必开)
CONFIG_REGULATOR=y
# 提供线性范围工具库(自动被select)
CONFIG_LINEAR_RANGES=y

# 调试(量产关闭，开发板可开)
# CONFIG_REGULATOR_DEBUG is not set

# 通用基础调压驱动
CONFIG_REGULATOR_FIXED_VOLTAGE=y
CONFIG_REGULATOR_VIRTUAL_CONSUMER=m
CONFIG_REGULATOR_USERSPACE_CONSUMER=y
CONFIG_REGULATOR_NETLINK_EVENTS=y

# GPIO调压备用(外设简单电源开关)
CONFIG_REGULATOR_GPIO=y

# Rockchip PMIC电源管理芯片(H29K标配RK8xx系列)
CONFIG_REGULATOR_RK808=y

# PWM电压调压器【重点，PWM调压驱动本体】
# 依赖 CONFIG_PWM=y (drivers/pwm子系统必须同步开启)
CONFIG_REGULATOR_PWM=y

# 无关厂商PMIC全部关闭(精简内核)
# CONFIG_REGULATOR_88PG86X is not set
# CONFIG_REGULATOR_88PM800 is not set
# CONFIG_REGULATOR_ACT8865 is not set
# CONFIG_REGULATOR_AXP20X is not set
# CONFIG_REGULATOR_DA90XX is not set
# CONFIG_REGULATOR_MAXXXX is not set
# CONFIG_REGULATOR_QCOM_XXX is not set
# CONFIG_REGULATOR_MTXXX is not set
# CONFIG_REGULATOR_TI_XXX is not set

EOF
echo "✅ H29K 内核参数注入完成"
